CREATE OR REPLACE PROCEDURE CONTROL.REFRESH_DATASET_HEALTH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO CONTROL.DATASET_HEALTH AS TARGET
    USING (
        WITH POLICY AS (
            SELECT
                DATASET_ID,
                MAX(IFF(STAGE = 'SOURCE_TO_BRONZE' AND ENABLED, MAX_LATENCY_SECONDS, NULL)) AS SOURCE_TO_BRONZE_MAX_LATENCY_SECONDS,
                MAX(IFF(STAGE = 'BRONZE_TO_SILVER' AND ENABLED, MAX_LATENCY_SECONDS, NULL)) AS BRONZE_TO_SILVER_MAX_LATENCY_SECONDS,
                MAX(IFF(STAGE = 'SILVER_TO_GOLD' AND ENABLED, MAX_LATENCY_SECONDS, NULL)) AS SILVER_TO_GOLD_MAX_LATENCY_SECONDS,
                MAX(IFF(STAGE = 'END_TO_END' AND ENABLED, MAX_FRESHNESS_SECONDS, NULL)) AS END_TO_END_MAX_FRESHNESS_SECONDS
            FROM CONTROL.SLA_POLICY
            GROUP BY DATASET_ID
        ),
        OPEN_INCIDENT AS (
            SELECT DATASET_ID, COUNT(*) AS OPEN_INCIDENT_COUNT
            FROM CONTROL.INCIDENT
            WHERE STATUS = 'OPEN'
            GROUP BY DATASET_ID
        ),
        EVALUATED AS (
            SELECT
                O.DATASET_ID,
                CURRENT_TIMESTAMP() AS EVALUATED_AT,
                O.ACTIVE_VERSION,
                O.INGESTION_STATUS,
                O.SILVER_STATUS,
                O.GOLD_STATUS,
                O.LAST_SOURCE_EVENT_AT,
                O.LAST_BRONZE_AT,
                O.LAST_SILVER_AT,
                O.LAST_GOLD_AT,
                O.SOURCE_TO_BRONZE_LATENCY_SECONDS,
                O.BRONZE_TO_SILVER_LATENCY_SECONDS,
                O.SILVER_TO_GOLD_LATENCY_SECONDS,
                IFF(
                    O.LATEST_DATA_AT IS NULL,
                    NULL,
                    GREATEST(0, DATEDIFF('SECOND', O.LATEST_DATA_AT, CURRENT_TIMESTAMP()))
                ) AS FRESHNESS_SECONDS,
                COALESCE(I.OPEN_INCIDENT_COUNT, 0) AS OPEN_INCIDENT_COUNT,
                CASE
                    WHEN O.ENABLED = FALSE THEN 'PAUSED'
                    WHEN O.ACTIVE_VERSION IS NULL THEN 'DEVELOPMENT'
                    WHEN O.INGESTION_STATUS = 'FAILED' OR O.SILVER_STATUS = 'FAILED' OR O.GOLD_STATUS = 'FAILED' THEN 'RED'
                    WHEN P.SOURCE_TO_BRONZE_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.SOURCE_TO_BRONZE_LATENCY_SECONDS > P.SOURCE_TO_BRONZE_MAX_LATENCY_SECONDS THEN 'RED'
                    WHEN P.BRONZE_TO_SILVER_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.BRONZE_TO_SILVER_LATENCY_SECONDS > P.BRONZE_TO_SILVER_MAX_LATENCY_SECONDS THEN 'RED'
                    WHEN P.SILVER_TO_GOLD_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.SILVER_TO_GOLD_LATENCY_SECONDS > P.SILVER_TO_GOLD_MAX_LATENCY_SECONDS THEN 'RED'
                    WHEN P.END_TO_END_MAX_FRESHNESS_SECONDS IS NOT NULL
                         AND O.LATEST_DATA_AT IS NOT NULL
                         AND DATEDIFF('SECOND', O.LATEST_DATA_AT, CURRENT_TIMESTAMP()) > P.END_TO_END_MAX_FRESHNESS_SECONDS THEN 'RED'
                    WHEN O.LATEST_DATA_AT IS NULL THEN 'YELLOW'
                    ELSE 'GREEN'
                END AS OVERALL_STATUS,
                CASE
                    WHEN P.SOURCE_TO_BRONZE_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.SOURCE_TO_BRONZE_LATENCY_SECONDS > P.SOURCE_TO_BRONZE_MAX_LATENCY_SECONDS THEN 'VIOLATED'
                    WHEN P.BRONZE_TO_SILVER_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.BRONZE_TO_SILVER_LATENCY_SECONDS > P.BRONZE_TO_SILVER_MAX_LATENCY_SECONDS THEN 'VIOLATED'
                    WHEN P.SILVER_TO_GOLD_MAX_LATENCY_SECONDS IS NOT NULL
                         AND O.SILVER_TO_GOLD_LATENCY_SECONDS > P.SILVER_TO_GOLD_MAX_LATENCY_SECONDS THEN 'VIOLATED'
                    WHEN P.END_TO_END_MAX_FRESHNESS_SECONDS IS NOT NULL
                         AND O.LATEST_DATA_AT IS NOT NULL
                         AND DATEDIFF('SECOND', O.LATEST_DATA_AT, CURRENT_TIMESTAMP()) > P.END_TO_END_MAX_FRESHNESS_SECONDS THEN 'VIOLATED'
                    WHEN P.DATASET_ID IS NULL THEN 'UNDEFINED'
                    WHEN O.LATEST_DATA_AT IS NULL THEN 'UNKNOWN'
                    ELSE 'PASS'
                END AS SLA_STATUS
            FROM CONTROL.DATASET_OBSERVABILITY_V O
            LEFT JOIN POLICY P ON P.DATASET_ID = O.DATASET_ID
            LEFT JOIN OPEN_INCIDENT I ON I.DATASET_ID = O.DATASET_ID
        )
        SELECT * FROM EVALUATED
    ) AS SOURCE
    ON TARGET.DATASET_ID = SOURCE.DATASET_ID
    WHEN MATCHED THEN UPDATE SET
        EVALUATED_AT = SOURCE.EVALUATED_AT,
        ACTIVE_VERSION = SOURCE.ACTIVE_VERSION,
        INGESTION_STATUS = SOURCE.INGESTION_STATUS,
        SILVER_STATUS = SOURCE.SILVER_STATUS,
        GOLD_STATUS = SOURCE.GOLD_STATUS,
        LAST_SOURCE_EVENT_AT = SOURCE.LAST_SOURCE_EVENT_AT,
        LAST_BRONZE_AT = SOURCE.LAST_BRONZE_AT,
        LAST_SILVER_AT = SOURCE.LAST_SILVER_AT,
        LAST_GOLD_AT = SOURCE.LAST_GOLD_AT,
        SOURCE_TO_BRONZE_LATENCY_SECONDS = SOURCE.SOURCE_TO_BRONZE_LATENCY_SECONDS,
        BRONZE_TO_SILVER_LATENCY_SECONDS = SOURCE.BRONZE_TO_SILVER_LATENCY_SECONDS,
        SILVER_TO_GOLD_LATENCY_SECONDS = SOURCE.SILVER_TO_GOLD_LATENCY_SECONDS,
        FRESHNESS_SECONDS = SOURCE.FRESHNESS_SECONDS,
        SLA_STATUS = SOURCE.SLA_STATUS,
        OPEN_INCIDENT_COUNT = SOURCE.OPEN_INCIDENT_COUNT,
        OVERALL_STATUS = SOURCE.OVERALL_STATUS,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        DATASET_ID,
        EVALUATED_AT,
        ACTIVE_VERSION,
        INGESTION_STATUS,
        SILVER_STATUS,
        GOLD_STATUS,
        LAST_SOURCE_EVENT_AT,
        LAST_BRONZE_AT,
        LAST_SILVER_AT,
        LAST_GOLD_AT,
        SOURCE_TO_BRONZE_LATENCY_SECONDS,
        BRONZE_TO_SILVER_LATENCY_SECONDS,
        SILVER_TO_GOLD_LATENCY_SECONDS,
        FRESHNESS_SECONDS,
        SLA_STATUS,
        OPEN_INCIDENT_COUNT,
        OVERALL_STATUS,
        UPDATED_AT
    ) VALUES (
        SOURCE.DATASET_ID,
        SOURCE.EVALUATED_AT,
        SOURCE.ACTIVE_VERSION,
        SOURCE.INGESTION_STATUS,
        SOURCE.SILVER_STATUS,
        SOURCE.GOLD_STATUS,
        SOURCE.LAST_SOURCE_EVENT_AT,
        SOURCE.LAST_BRONZE_AT,
        SOURCE.LAST_SILVER_AT,
        SOURCE.LAST_GOLD_AT,
        SOURCE.SOURCE_TO_BRONZE_LATENCY_SECONDS,
        SOURCE.BRONZE_TO_SILVER_LATENCY_SECONDS,
        SOURCE.SILVER_TO_GOLD_LATENCY_SECONDS,
        SOURCE.FRESHNESS_SECONDS,
        SOURCE.SLA_STATUS,
        SOURCE.OPEN_INCIDENT_COUNT,
        SOURCE.OVERALL_STATUS,
        CURRENT_TIMESTAMP()
    );

    RETURN 'DATASET_HEALTH refreshed';
END;
$$;

-- Schedule this procedure with a domain-owned Snowflake task when the domain
-- is ready for live health evaluation. The framework intentionally does not
-- create/resume a warehouse-backed task automatically during project init.
