-- Normalized data-quality and reconciliation evidence for one domain.
-- Dataset-specific checks remain explicit SQL owned by the dataset implementation.
-- This control-plane migration stores/evaluates results; it is not a generic DQ rule engine.

CREATE TABLE IF NOT EXISTS CONTROL.DQ_RESULT (
    RESULT_ID VARCHAR NOT NULL,
    RUN_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    VERSION VARCHAR NOT NULL,
    CHECK_ID VARCHAR NOT NULL,
    CHECK_SEVERITY VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    VIOLATION_COUNT NUMBER(38,0),
    DETAILS VARIANT,
    QUERY_ID VARCHAR,
    CHECKED_AT TIMESTAMP_LTZ NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.RECONCILIATION_RESULT (
    RESULT_ID VARCHAR NOT NULL,
    RUN_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    VERSION VARCHAR,
    STAGE VARCHAR NOT NULL,
    CHECK_ID VARCHAR NOT NULL,
    CHECK_SEVERITY VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    SOURCE_VALUE VARCHAR,
    TARGET_VALUE VARCHAR,
    DIFFERENCE_VALUE VARCHAR,
    DETAILS VARIANT,
    QUERY_ID VARCHAR,
    CHECKED_AT TIMESTAMP_LTZ NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE CONTROL.RECORD_DQ_RESULT(
    P_RUN_ID VARCHAR,
    P_DATASET_ID VARCHAR,
    P_VERSION VARCHAR,
    P_CHECK_ID VARCHAR,
    P_CHECK_SEVERITY VARCHAR,
    P_STATUS VARCHAR,
    P_VIOLATION_COUNT NUMBER,
    P_DETAILS VARIANT
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RESULT_ID VARCHAR DEFAULT UUID_STRING();
BEGIN
    INSERT INTO CONTROL.DQ_RESULT (
        RESULT_ID, RUN_ID, DATASET_ID, VERSION, CHECK_ID, CHECK_SEVERITY,
        STATUS, VIOLATION_COUNT, DETAILS, QUERY_ID, CHECKED_AT
    ) VALUES (
        :V_RESULT_ID, :P_RUN_ID, :P_DATASET_ID, :P_VERSION, :P_CHECK_ID,
        UPPER(:P_CHECK_SEVERITY), UPPER(:P_STATUS), :P_VIOLATION_COUNT,
        :P_DETAILS, LAST_QUERY_ID(), CURRENT_TIMESTAMP()
    );
    RETURN V_RESULT_ID;
END;
$$;

CREATE OR REPLACE PROCEDURE CONTROL.RECORD_RECONCILIATION_RESULT(
    P_RUN_ID VARCHAR,
    P_DATASET_ID VARCHAR,
    P_VERSION VARCHAR,
    P_STAGE VARCHAR,
    P_CHECK_ID VARCHAR,
    P_CHECK_SEVERITY VARCHAR,
    P_STATUS VARCHAR,
    P_SOURCE_VALUE VARCHAR,
    P_TARGET_VALUE VARCHAR,
    P_DIFFERENCE_VALUE VARCHAR,
    P_DETAILS VARIANT
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RESULT_ID VARCHAR DEFAULT UUID_STRING();
BEGIN
    INSERT INTO CONTROL.RECONCILIATION_RESULT (
        RESULT_ID, RUN_ID, DATASET_ID, VERSION, STAGE, CHECK_ID,
        CHECK_SEVERITY, STATUS, SOURCE_VALUE, TARGET_VALUE, DIFFERENCE_VALUE,
        DETAILS, QUERY_ID, CHECKED_AT
    ) VALUES (
        :V_RESULT_ID, :P_RUN_ID, :P_DATASET_ID, :P_VERSION, UPPER(:P_STAGE), :P_CHECK_ID,
        UPPER(:P_CHECK_SEVERITY), UPPER(:P_STATUS), :P_SOURCE_VALUE, :P_TARGET_VALUE,
        :P_DIFFERENCE_VALUE, :P_DETAILS, LAST_QUERY_ID(), CURRENT_TIMESTAMP()
    );
    RETURN V_RESULT_ID;
END;
$$;

CREATE OR REPLACE VIEW CONTROL.DQ_LATEST_RUN_V AS
WITH RUN_SUMMARY AS (
    SELECT
        DATASET_ID,
        VERSION,
        RUN_ID,
        MAX(CHECKED_AT) AS CHECKED_AT,
        COUNT(*) AS CHECK_COUNT,
        COUNT_IF(UPPER(STATUS) = 'FAIL' AND UPPER(CHECK_SEVERITY) <> 'WARN') AS ERROR_FAILURE_COUNT,
        COUNT_IF(UPPER(STATUS) = 'FAIL' AND UPPER(CHECK_SEVERITY) = 'WARN') AS WARN_FAILURE_COUNT,
        LISTAGG(
            IFF(UPPER(STATUS) = 'FAIL', CHECK_ID, NULL),
            ', '
        ) WITHIN GROUP (ORDER BY CHECK_ID) AS FAILED_CHECKS
    FROM CONTROL.DQ_RESULT
    GROUP BY DATASET_ID, VERSION, RUN_ID
),
RANKED AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY DATASET_ID, VERSION
            ORDER BY CHECKED_AT DESC, RUN_ID DESC
        ) AS RN
    FROM RUN_SUMMARY
)
SELECT
    DATASET_ID,
    VERSION,
    RUN_ID,
    CHECKED_AT,
    CHECK_COUNT,
    ERROR_FAILURE_COUNT,
    WARN_FAILURE_COUNT,
    FAILED_CHECKS,
    CASE
        WHEN ERROR_FAILURE_COUNT > 0 THEN 'FAILED'
        WHEN WARN_FAILURE_COUNT > 0 THEN 'WARNING'
        ELSE 'PASS'
    END AS DQ_STATUS
FROM RANKED
WHERE RN = 1;

CREATE OR REPLACE VIEW CONTROL.RECONCILIATION_LATEST_STAGE_V AS
WITH RUN_SUMMARY AS (
    SELECT
        DATASET_ID,
        VERSION,
        UPPER(STAGE) AS STAGE,
        RUN_ID,
        MAX(CHECKED_AT) AS CHECKED_AT,
        COUNT(*) AS CHECK_COUNT,
        COUNT_IF(UPPER(STATUS) = 'FAIL' AND UPPER(CHECK_SEVERITY) <> 'WARN') AS ERROR_FAILURE_COUNT,
        COUNT_IF(UPPER(STATUS) = 'FAIL' AND UPPER(CHECK_SEVERITY) = 'WARN') AS WARN_FAILURE_COUNT,
        LISTAGG(
            IFF(UPPER(STATUS) = 'FAIL', CHECK_ID, NULL),
            ', '
        ) WITHIN GROUP (ORDER BY CHECK_ID) AS FAILED_CHECKS
    FROM CONTROL.RECONCILIATION_RESULT
    GROUP BY DATASET_ID, VERSION, UPPER(STAGE), RUN_ID
),
RANKED AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY DATASET_ID, COALESCE(VERSION, '<UNVERSIONED>'), STAGE
            ORDER BY CHECKED_AT DESC, RUN_ID DESC
        ) AS RN
    FROM RUN_SUMMARY
)
SELECT
    DATASET_ID,
    VERSION,
    STAGE,
    RUN_ID,
    CHECKED_AT,
    CHECK_COUNT,
    ERROR_FAILURE_COUNT,
    WARN_FAILURE_COUNT,
    FAILED_CHECKS,
    CASE
        WHEN ERROR_FAILURE_COUNT > 0 THEN 'FAILED'
        WHEN WARN_FAILURE_COUNT > 0 THEN 'WARNING'
        ELSE 'PASS'
    END AS RECONCILIATION_STATUS
FROM RANKED
WHERE RN = 1;

CREATE OR REPLACE VIEW CONTROL.RECONCILIATION_ACTIVE_STAGE_V AS
WITH CANDIDATE AS (
    SELECT
        R.*,
        D.ACTIVE_VERSION,
        ROW_NUMBER() OVER (
            PARTITION BY R.DATASET_ID, R.STAGE
            ORDER BY
                R.CHECKED_AT DESC,
                IFF(R.VERSION = D.ACTIVE_VERSION, 1, 0) DESC,
                R.RUN_ID DESC
        ) AS RN
    FROM CONTROL.RECONCILIATION_LATEST_STAGE_V R
    JOIN CONTROL.DATASET D
      ON D.DATASET_ID = R.DATASET_ID
    WHERE R.VERSION IS NULL OR R.VERSION = D.ACTIVE_VERSION
)
SELECT
    DATASET_ID,
    ACTIVE_VERSION,
    VERSION AS EVIDENCE_VERSION,
    STAGE,
    RUN_ID,
    CHECKED_AT,
    CHECK_COUNT,
    ERROR_FAILURE_COUNT,
    WARN_FAILURE_COUNT,
    FAILED_CHECKS,
    RECONCILIATION_STATUS
FROM CANDIDATE
WHERE RN = 1;

CREATE OR REPLACE VIEW CONTROL.DATASET_QUALITY_STATUS_V AS
WITH ACTIVE_DQ AS (
    SELECT
        D.DATASET_ID,
        D.ACTIVE_VERSION,
        Q.RUN_ID,
        Q.CHECKED_AT,
        Q.DQ_STATUS,
        Q.ERROR_FAILURE_COUNT,
        Q.WARN_FAILURE_COUNT,
        Q.FAILED_CHECKS
    FROM CONTROL.DATASET D
    LEFT JOIN CONTROL.DQ_LATEST_RUN_V Q
      ON Q.DATASET_ID = D.DATASET_ID
     AND Q.VERSION = D.ACTIVE_VERSION
),
RECON AS (
    SELECT
        DATASET_ID,
        MAX(CHECKED_AT) AS CHECKED_AT,
        COUNT_IF(RECONCILIATION_STATUS = 'FAILED') AS FAILED_STAGE_COUNT,
        COUNT_IF(RECONCILIATION_STATUS = 'WARNING') AS WARNING_STAGE_COUNT,
        LISTAGG(
            IFF(RECONCILIATION_STATUS IN ('FAILED', 'WARNING'), STAGE || ': ' || COALESCE(FAILED_CHECKS, 'check failed'), NULL),
            '; '
        ) WITHIN GROUP (ORDER BY STAGE) AS RECONCILIATION_REASON
    FROM CONTROL.RECONCILIATION_ACTIVE_STAGE_V
    GROUP BY DATASET_ID
)
SELECT
    D.DATASET_ID,
    D.ACTIVE_VERSION,
    COALESCE(Q.DQ_STATUS, 'UNASSESSED') AS DQ_STATUS,
    Q.CHECKED_AT AS LAST_DQ_AT,
    Q.FAILED_CHECKS AS DQ_FAILED_CHECKS,
    CASE
        WHEN R.DATASET_ID IS NULL THEN 'UNASSESSED'
        WHEN R.FAILED_STAGE_COUNT > 0 THEN 'FAILED'
        WHEN R.WARNING_STAGE_COUNT > 0 THEN 'WARNING'
        ELSE 'PASS'
    END AS RECONCILIATION_STATUS,
    R.CHECKED_AT AS LAST_RECONCILIATION_AT,
    R.RECONCILIATION_REASON,
    CASE
        WHEN Q.DQ_STATUS = 'FAILED' THEN 'DQ failed: ' || COALESCE(Q.FAILED_CHECKS, 'one or more checks')
        WHEN Q.DQ_STATUS = 'WARNING' THEN 'DQ warning: ' || COALESCE(Q.FAILED_CHECKS, 'one or more checks')
        ELSE NULL
    END AS DQ_REASON
FROM CONTROL.DATASET D
LEFT JOIN ACTIVE_DQ Q ON Q.DATASET_ID = D.DATASET_ID
LEFT JOIN RECON R ON R.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE VIEW CONTROL.DATASET_QUALITY_DETAIL_V AS
SELECT
    D.DATASET_ID,
    D.ACTIVE_VERSION,
    Q.DQ_STATUS,
    Q.LAST_DQ_AT,
    Q.DQ_FAILED_CHECKS,
    Q.RECONCILIATION_STATUS,
    Q.LAST_RECONCILIATION_AT,
    Q.DQ_REASON,
    Q.RECONCILIATION_REASON
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_QUALITY_STATUS_V Q
  ON Q.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE PROCEDURE CONTROL.EVALUATE_QUALITY_INCIDENTS()
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_ACTIVE_CONDITIONS NUMBER DEFAULT 0;
    V_OPEN_INCIDENTS NUMBER DEFAULT 0;
BEGIN
    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_ACTIVE_QUALITY_CONDITIONS (
        INCIDENT_KEY VARCHAR,
        DATASET_ID VARCHAR,
        INCIDENT_TYPE VARCHAR,
        STAGE VARCHAR,
        SEVERITY VARCHAR,
        REASON VARCHAR,
        LATEST_MESSAGE VARCHAR
    );

    INSERT INTO ESF_ACTIVE_QUALITY_CONDITIONS
    SELECT
        D.DATASET_ID || '|DQ_FAILURE|',
        D.DATASET_ID,
        'DQ_FAILURE',
        'SILVER',
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        'latest active-version data-quality run failed',
        'Failed checks: ' || COALESCE(Q.FAILED_CHECKS, 'one or more checks')
    FROM CONTROL.DATASET D
    JOIN CONTROL.DQ_LATEST_RUN_V Q
      ON Q.DATASET_ID = D.DATASET_ID
     AND Q.VERSION = D.ACTIVE_VERSION
    WHERE D.ENABLED
      AND Q.ERROR_FAILURE_COUNT > 0;

    INSERT INTO ESF_ACTIVE_QUALITY_CONDITIONS
    SELECT
        D.DATASET_ID || '|RECONCILIATION_FAILURE|' || R.STAGE,
        D.DATASET_ID,
        'RECONCILIATION_FAILURE',
        R.STAGE,
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        'latest reconciliation failed',
        R.STAGE || ' failed checks: ' || COALESCE(R.FAILED_CHECKS, 'one or more checks')
    FROM CONTROL.RECONCILIATION_ACTIVE_STAGE_V R
    JOIN CONTROL.DATASET D ON D.DATASET_ID = R.DATASET_ID
    WHERE D.ENABLED
      AND R.ERROR_FAILURE_COUNT > 0;

    V_ACTIVE_CONDITIONS := (SELECT COUNT(*) FROM ESF_ACTIVE_QUALITY_CONDITIONS);

    UPDATE CONTROL.INCIDENT I
    SET
        SEVERITY = A.SEVERITY,
        STAGE = A.STAGE,
        REASON = A.REASON,
        LATEST_MESSAGE = A.LATEST_MESSAGE,
        UPDATED_AT = CURRENT_TIMESTAMP()
    FROM ESF_ACTIVE_QUALITY_CONDITIONS A
    WHERE I.INCIDENT_KEY = A.INCIDENT_KEY
      AND I.STATUS = 'OPEN';

    INSERT INTO CONTROL.INCIDENT (
        INCIDENT_ID, INCIDENT_KEY, DATASET_ID, INCIDENT_TYPE, STAGE,
        SEVERITY, STATUS, OPENED_AT, REASON, LATEST_MESSAGE
    )
    SELECT
        UUID_STRING(), A.INCIDENT_KEY, A.DATASET_ID, A.INCIDENT_TYPE, A.STAGE,
        A.SEVERITY, 'OPEN', CURRENT_TIMESTAMP(), A.REASON, A.LATEST_MESSAGE
    FROM ESF_ACTIVE_QUALITY_CONDITIONS A
    WHERE NOT EXISTS (
        SELECT 1
        FROM CONTROL.INCIDENT I
        WHERE I.INCIDENT_KEY = A.INCIDENT_KEY
          AND I.STATUS = 'OPEN'
    );

    UPDATE CONTROL.INCIDENT I
    SET
        STATUS = 'RESOLVED',
        RESOLVED_AT = CURRENT_TIMESTAMP(),
        LATEST_MESSAGE = 'Quality condition recovered',
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE I.STATUS = 'OPEN'
      AND I.INCIDENT_TYPE IN ('DQ_FAILURE', 'RECONCILIATION_FAILURE')
      AND NOT EXISTS (
          SELECT 1
          FROM ESF_ACTIVE_QUALITY_CONDITIONS A
          WHERE A.INCIDENT_KEY = I.INCIDENT_KEY
      );

    V_OPEN_INCIDENTS := (
        SELECT COUNT(*)
        FROM CONTROL.INCIDENT
        WHERE STATUS = 'OPEN'
          AND INCIDENT_TYPE IN ('DQ_FAILURE', 'RECONCILIATION_FAILURE')
    );

    RETURN OBJECT_CONSTRUCT(
        'active_quality_conditions', V_ACTIVE_CONDITIONS,
        'open_quality_incidents', V_OPEN_INCIDENTS,
        'evaluated_at', CURRENT_TIMESTAMP()
    );
END;
$$;

CREATE TASK IF NOT EXISTS CONTROL.EVALUATE_QUALITY_INCIDENTS_TASK
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    SCHEDULE = '1 MINUTE'
    USER_TASK_TIMEOUT_MS = 60000
    SUSPEND_TASK_AFTER_NUM_FAILURES = 3
AS
    CALL CONTROL.EVALUATE_QUALITY_INCIDENTS();

-- Explicit go-live after migration validation:
-- ALTER TASK CONTROL.EVALUATE_QUALITY_INCIDENTS_TASK RESUME;

CREATE OR REPLACE VIEW CONTROL.DATASET_HEALTH_V AS
WITH OPEN_INCIDENT AS (
    SELECT DATASET_ID, COUNT(*) AS OPEN_INCIDENT_COUNT
    FROM CONTROL.INCIDENT
    WHERE STATUS = 'OPEN'
    GROUP BY DATASET_ID
)
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    UPPER(COALESCE(D.LIFECYCLE_STATUS, IFF(D.ENABLED, 'ACTIVE', 'PAUSED'))) AS LIFECYCLE_STATUS,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    H.EVALUATED_AT,
    H.INGESTION_STATUS,
    H.SILVER_STATUS,
    H.GOLD_STATUS,
    Q.DQ_STATUS,
    Q.RECONCILIATION_STATUS,
    Q.LAST_DQ_AT,
    Q.LAST_RECONCILIATION_AT,
    H.LAST_SOURCE_EVENT_AT,
    H.LAST_BRONZE_AT,
    H.LAST_SILVER_AT,
    H.LAST_GOLD_AT,
    H.SOURCE_TO_BRONZE_LATENCY_SECONDS,
    H.BRONZE_TO_SILVER_LATENCY_SECONDS,
    H.SILVER_TO_GOLD_LATENCY_SECONDS,
    H.FRESHNESS_SECONDS,
    H.SLA_STATUS,
    CASE
        WHEN H.HEALTH_REASON IS NULL THEN COALESCE(Q.DQ_REASON, Q.RECONCILIATION_REASON)
        WHEN Q.DQ_REASON IS NULL AND Q.RECONCILIATION_REASON IS NULL THEN H.HEALTH_REASON
        ELSE H.HEALTH_REASON || '; ' || COALESCE(Q.DQ_REASON || '; ', '') || COALESCE(Q.RECONCILIATION_REASON, '')
    END AS HEALTH_REASON,
    COALESCE(I.OPEN_INCIDENT_COUNT, 0) AS OPEN_INCIDENT_COUNT,
    CASE
        WHEN UPPER(D.LIFECYCLE_STATUS) = 'DECOMMISSIONED' THEN 'DECOMMISSIONED'
        WHEN UPPER(D.LIFECYCLE_STATUS) = 'PAUSED' OR D.ENABLED = FALSE THEN 'PAUSED'
        WHEN H.OVERALL_STATUS = 'RED'
          OR Q.DQ_STATUS = 'FAILED'
          OR Q.RECONCILIATION_STATUS = 'FAILED' THEN 'RED'
        WHEN H.OVERALL_STATUS = 'YELLOW'
          OR Q.DQ_STATUS = 'WARNING'
          OR Q.RECONCILIATION_STATUS = 'WARNING' THEN 'YELLOW'
        ELSE H.OVERALL_STATUS
    END AS OVERALL_STATUS
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_HEALTH H ON H.DATASET_ID = D.DATASET_ID
LEFT JOIN CONTROL.DATASET_QUALITY_STATUS_V Q ON Q.DATASET_ID = D.DATASET_ID
LEFT JOIN OPEN_INCIDENT I ON I.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE VIEW CONTROL.ENTERPRISE_HEALTH_EXPORT_V AS
SELECT
    '__PROJECT_CODE__'::VARCHAR AS DOMAIN_CODE,
    CURRENT_DATABASE() AS DOMAIN_DATABASE,
    DATASET_ID,
    SOURCE_ID,
    DATASET_NAME,
    OWNER,
    CRITICALITY,
    PATTERN,
    ENABLED,
    LIFECYCLE_STATUS,
    ACTIVE_VERSION,
    CANDIDATE_VERSION,
    EVALUATED_AT,
    INGESTION_STATUS,
    SILVER_STATUS,
    GOLD_STATUS,
    DQ_STATUS,
    RECONCILIATION_STATUS,
    LAST_DQ_AT,
    LAST_RECONCILIATION_AT,
    LAST_SOURCE_EVENT_AT,
    LAST_BRONZE_AT,
    LAST_SILVER_AT,
    LAST_GOLD_AT,
    SOURCE_TO_BRONZE_LATENCY_SECONDS,
    BRONZE_TO_SILVER_LATENCY_SECONDS,
    SILVER_TO_GOLD_LATENCY_SECONDS,
    FRESHNESS_SECONDS,
    SLA_STATUS,
    HEALTH_REASON,
    OPEN_INCIDENT_COUNT,
    OVERALL_STATUS
FROM CONTROL.DATASET_HEALTH_V;

CREATE OR REPLACE VIEW CONTROL.DOMAIN_HEALTH_SUMMARY_V AS
SELECT
    '__PROJECT_CODE__'::VARCHAR AS DOMAIN_CODE,
    CURRENT_DATABASE() AS DOMAIN_DATABASE,
    CURRENT_TIMESTAMP() AS OBSERVED_AT,
    COUNT(*) AS TOTAL_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'ACTIVE') AS ACTIVE_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'PAUSED') AS PAUSED_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'DECOMMISSIONED') AS DECOMMISSIONED_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'GREEN') AS GREEN_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'YELLOW') AS YELLOW_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'RED') AS RED_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'DEVELOPMENT') AS DEVELOPMENT_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS IS NULL) AS UNASSESSED_DATASET_COUNT,
    COUNT_IF(DQ_STATUS = 'FAILED') AS DQ_FAILED_DATASET_COUNT,
    COUNT_IF(RECONCILIATION_STATUS = 'FAILED') AS RECONCILIATION_FAILED_DATASET_COUNT,
    COALESCE(SUM(OPEN_INCIDENT_COUNT), 0) AS OPEN_INCIDENT_COUNT,
    MAX(EVALUATED_AT) AS LAST_EVALUATED_AT,
    MAX(LAST_DQ_AT) AS LAST_DQ_AT,
    MAX(LAST_RECONCILIATION_AT) AS LAST_RECONCILIATION_AT
FROM CONTROL.ENTERPRISE_HEALTH_EXPORT_V;
