-- Framework migration 140: enrich Dynamic Table observability with current Snowflake-native metadata.
--
-- Migration 100 established the Dynamic Table observability boundary. It is released and immutable.
-- This migration replaces only the existing normalization views; it does not create a second health
-- abstraction and does not fabricate CONTROL.PIPELINE_RUN rows for Dynamic Table refreshes.
--
-- INFORMATION_SCHEMA Dynamic Table functions retain recent history and require MONITOR visibility
-- for full metadata. Long-retention Account Usage reporting remains a separate reporting concern.

CREATE OR REPLACE VIEW CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V COPY GRANTS AS
WITH REFRESH_HISTORY AS (
    SELECT
        NAME,
        SCHEMA_NAME,
        DATABASE_NAME,
        STATE,
        STATE_CODE,
        STATE_MESSAGE,
        QUERY_ID,
        DATA_TIMESTAMP,
        REFRESH_START_TIME,
        REFRESH_END_TIME,
        COMPLETION_TARGET,
        QUALIFIED_NAME,
        REFRESH_ACTION,
        REINIT_REASON,
        REFRESH_TRIGGER,
        TARGET_LAG_SEC,
        STATISTICS,
        INPUTS_WITH_CHANGED_DATA
    FROM TABLE(
        INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
            DATA_TIMESTAMP_START => DATEADD('DAY', -7, CURRENT_TIMESTAMP()),
            RESULT_LIMIT => 10000
        )
    )
    WHERE STATE <> 'SCHEDULED'
),
CURRENT_TABLES AS (
    SELECT
        NAME,
        SCHEMA_NAME,
        DATABASE_NAME,
        QUALIFIED_NAME,
        TARGET_LAG_SEC,
        TARGET_LAG_TYPE,
        SCHEDULING_STATE:STATE::VARCHAR AS SCHEDULING_STATE,
        SCHEDULING_STATE:REASON_CODE::VARCHAR AS SCHEDULING_REASON_CODE,
        SCHEDULING_STATE:REASON_MESSAGE::VARCHAR AS SCHEDULING_REASON_MESSAGE,
        SCHEDULING_STATE:SUSPENDED_ON::TIMESTAMP_LTZ AS SUSPENDED_ON,
        SCHEDULING_STATE:RESUMED_ON::TIMESTAMP_LTZ AS RESUMED_ON,
        MEAN_LAG_SEC,
        MAXIMUM_LAG_SEC,
        TIME_ABOVE_TARGET_LAG_SEC,
        TIME_WITHIN_TARGET_LAG_RATIO,
        LATEST_DATA_TIMESTAMP,
        LAST_COMPLETED_REFRESH_STATE,
        LAST_COMPLETED_REFRESH_STATE_CODE,
        LAST_COMPLETED_REFRESH_STATE_MESSAGE,
        EXECUTING_REFRESH_QUERY_ID
    FROM TABLE(
        INFORMATION_SCHEMA.DYNAMIC_TABLES(
            REFRESH_DATA_TIMESTAMP_START => DATEADD('DAY', -7, CURRENT_TIMESTAMP()),
            RESULT_LIMIT => 10000
        )
    )
),
MATCHED AS (
    SELECT
        V.DATASET_ID,
        V.VERSION,
        V.PRIMARY_RUNTIME_OBJECT,
        R.STATE AS REFRESH_STATE,
        R.STATE_CODE,
        R.STATE_MESSAGE,
        R.QUERY_ID,
        R.DATA_TIMESTAMP,
        R.REFRESH_START_TIME,
        R.REFRESH_END_TIME,
        R.COMPLETION_TARGET,
        CASE
            WHEN R.STATE = 'EXECUTING' OR C.EXECUTING_REFRESH_QUERY_ID IS NOT NULL THEN 'RUNNING'
            WHEN COALESCE(R.STATE, C.LAST_COMPLETED_REFRESH_STATE) IN ('SUCCEEDED', 'SKIPPED') THEN 'SUCCESS'
            WHEN COALESCE(R.STATE, C.LAST_COMPLETED_REFRESH_STATE) IN ('FAILED', 'CANCELLED', 'UPSTREAM_FAILED') THEN 'FAILED'
            ELSE 'UNKNOWN'
        END AS SILVER_STATUS,
        R.REFRESH_ACTION,
        R.REFRESH_TRIGGER,
        R.REINIT_REASON,
        R.TARGET_LAG_SEC AS REFRESH_TARGET_LAG_SEC,
        R.STATISTICS AS REFRESH_STATISTICS,
        R.INPUTS_WITH_CHANGED_DATA,
        R.STATISTICS:numInsertedRows::NUMBER AS REFRESH_NUM_INSERTED_ROWS,
        R.STATISTICS:numDeletedRows::NUMBER AS REFRESH_NUM_DELETED_ROWS,
        R.STATISTICS:numCopiedRows::NUMBER AS REFRESH_NUM_COPIED_ROWS,
        R.STATISTICS:numAddedPartitions::NUMBER AS REFRESH_NUM_ADDED_PARTITIONS,
        R.STATISTICS:numRemovedPartitions::NUMBER AS REFRESH_NUM_REMOVED_PARTITIONS,
        R.STATISTICS:queuedTimeMs::NUMBER AS REFRESH_QUEUED_TIME_MS,
        R.STATISTICS:compilationTimeMs::NUMBER AS REFRESH_COMPILATION_TIME_MS,
        R.STATISTICS:executionTimeMs::NUMBER AS REFRESH_EXECUTION_TIME_MS,
        C.TARGET_LAG_SEC AS CURRENT_TARGET_LAG_SEC,
        C.TARGET_LAG_TYPE,
        C.SCHEDULING_STATE,
        C.SCHEDULING_REASON_CODE,
        C.SCHEDULING_REASON_MESSAGE,
        C.SUSPENDED_ON,
        C.RESUMED_ON,
        C.MEAN_LAG_SEC,
        C.MAXIMUM_LAG_SEC,
        C.TIME_ABOVE_TARGET_LAG_SEC,
        C.TIME_WITHIN_TARGET_LAG_RATIO,
        C.LATEST_DATA_TIMESTAMP,
        C.LAST_COMPLETED_REFRESH_STATE,
        C.LAST_COMPLETED_REFRESH_STATE_CODE,
        C.LAST_COMPLETED_REFRESH_STATE_MESSAGE,
        C.EXECUTING_REFRESH_QUERY_ID
    FROM CONTROL.DATASET_VERSION V
    LEFT JOIN REFRESH_HISTORY R
      ON UPPER(V.PRIMARY_RUNTIME_OBJECT) = UPPER(R.SCHEMA_NAME || '.' || R.NAME)
    LEFT JOIN CURRENT_TABLES C
      ON UPPER(V.PRIMARY_RUNTIME_OBJECT) = UPPER(C.SCHEMA_NAME || '.' || C.NAME)
    WHERE V.EXECUTION_MODEL = 'dynamic_table'
)
SELECT *
FROM MATCHED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DATASET_ID, VERSION
    ORDER BY COALESCE(REFRESH_END_TIME, REFRESH_START_TIME, DATA_TIMESTAMP) DESC NULLS LAST
) = 1;

-- Keep one unified dataset observability boundary. Dynamic Table-specific diagnostic detail stays in
-- CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V; this view exposes only the compact fields useful for normal
-- operational triage alongside the existing cross-execution-model health contract.
CREATE OR REPLACE VIEW CONTROL.DATASET_OBSERVABILITY_V COPY GRANTS AS
WITH LATEST_INGESTION AS (
    SELECT *
    FROM CONTROL.INGESTION_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_PIPELINE AS (
    SELECT *
    FROM CONTROL.PIPELINE_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID, VERSION
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_DBT AS (
    SELECT *
    FROM CONTROL.DBT_RUN
    WHERE DATASET_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
)
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    V.EXECUTION_MODEL AS ACTIVE_EXECUTION_MODEL,
    I.STATUS AS INGESTION_STATUS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.SILVER_STATUS, P.STATUS) AS SILVER_STATUS,
    B.STATUS AS GOLD_STATUS,
    I.SOURCE_MAX_TIMESTAMP AS LAST_SOURCE_EVENT_AT,
    I.BRONZE_PUBLISHED_AT AS LAST_BRONZE_AT,
    IFF(
        V.EXECUTION_MODEL = 'dynamic_table',
        COALESCE(R.REFRESH_END_TIME, R.REFRESH_START_TIME),
        P.SILVER_PUBLISHED_AT
    ) AS LAST_SILVER_AT,
    B.GOLD_PUBLISHED_AT AS LAST_GOLD_AT,
    IFF(
        I.SOURCE_MAX_TIMESTAMP IS NULL OR I.BRONZE_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', I.SOURCE_MAX_TIMESTAMP, I.BRONZE_PUBLISHED_AT)
    ) AS SOURCE_TO_BRONZE_LATENCY_SECONDS,
    IFF(
        V.EXECUTION_MODEL = 'dynamic_table',
        IFF(
            COALESCE(R.DATA_TIMESTAMP, R.LATEST_DATA_TIMESTAMP) IS NULL OR R.REFRESH_END_TIME IS NULL,
            NULL,
            DATEDIFF(
                'SECOND',
                COALESCE(R.DATA_TIMESTAMP, R.LATEST_DATA_TIMESTAMP),
                R.REFRESH_END_TIME
            )
        ),
        IFF(
            P.BRONZE_DATA_MAX_AT IS NULL OR P.SILVER_PUBLISHED_AT IS NULL,
            NULL,
            DATEDIFF('SECOND', P.BRONZE_DATA_MAX_AT, P.SILVER_PUBLISHED_AT)
        )
    ) AS BRONZE_TO_SILVER_LATENCY_SECONDS,
    IFF(
        B.SILVER_DATA_MAX_AT IS NULL OR B.GOLD_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', B.SILVER_DATA_MAX_AT, B.GOLD_PUBLISHED_AT)
    ) AS SILVER_TO_GOLD_LATENCY_SECONDS,
    COALESCE(
        B.GOLD_DATA_MAX_AT,
        IFF(
            V.EXECUTION_MODEL = 'dynamic_table',
            COALESCE(R.DATA_TIMESTAMP, R.LATEST_DATA_TIMESTAMP),
            P.SILVER_DATA_MAX_AT
        ),
        I.SOURCE_MAX_TIMESTAMP
    ) AS LATEST_DATA_AT,
    I.RUN_ID AS LAST_INGESTION_RUN_ID,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', NULL, P.RUN_ID) AS LAST_PIPELINE_RUN_ID,
    B.RUN_ID AS LAST_DBT_RUN_ID,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.SCHEDULING_STATE, NULL) AS DYNAMIC_TABLE_SCHEDULING_STATE,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.SCHEDULING_REASON_CODE, NULL) AS DYNAMIC_TABLE_SCHEDULING_REASON_CODE,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.SCHEDULING_REASON_MESSAGE, NULL) AS DYNAMIC_TABLE_SCHEDULING_REASON_MESSAGE,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.CURRENT_TARGET_LAG_SEC, NULL) AS DYNAMIC_TABLE_TARGET_LAG_SECONDS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.MEAN_LAG_SEC, NULL) AS DYNAMIC_TABLE_MEAN_LAG_SECONDS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.MAXIMUM_LAG_SEC, NULL) AS DYNAMIC_TABLE_MAXIMUM_LAG_SECONDS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.TIME_ABOVE_TARGET_LAG_SEC, NULL) AS DYNAMIC_TABLE_TIME_ABOVE_TARGET_LAG_SECONDS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.TIME_WITHIN_TARGET_LAG_RATIO, NULL) AS DYNAMIC_TABLE_TIME_WITHIN_TARGET_LAG_RATIO,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REFRESH_ACTION, NULL) AS DYNAMIC_TABLE_REFRESH_ACTION,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REFRESH_TRIGGER, NULL) AS DYNAMIC_TABLE_REFRESH_TRIGGER,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REINIT_REASON, NULL) AS DYNAMIC_TABLE_REINIT_REASON,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REFRESH_QUEUED_TIME_MS, NULL) AS DYNAMIC_TABLE_REFRESH_QUEUED_TIME_MS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REFRESH_COMPILATION_TIME_MS, NULL) AS DYNAMIC_TABLE_REFRESH_COMPILATION_TIME_MS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.REFRESH_EXECUTION_TIME_MS, NULL) AS DYNAMIC_TABLE_REFRESH_EXECUTION_TIME_MS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', COALESCE(R.EXECUTING_REFRESH_QUERY_ID, R.QUERY_ID), NULL) AS DYNAMIC_TABLE_REFRESH_QUERY_ID
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_VERSION V
  ON V.DATASET_ID = D.DATASET_ID
 AND V.VERSION = D.ACTIVE_VERSION
LEFT JOIN LATEST_INGESTION I
  ON I.DATASET_ID = D.DATASET_ID
LEFT JOIN LATEST_PIPELINE P
  ON P.DATASET_ID = D.DATASET_ID
 AND P.VERSION = D.ACTIVE_VERSION
LEFT JOIN CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V R
  ON R.DATASET_ID = D.DATASET_ID
 AND R.VERSION = D.ACTIVE_VERSION
LEFT JOIN LATEST_DBT B
  ON B.DATASET_ID = D.DATASET_ID;
