-- SLA / cadence evaluation and automatic incident lifecycle.
-- This migration intentionally replaces the foundation REFRESH_DATASET_HEALTH procedure
-- with a richer domain-local evaluator. It does not route transformation logic.

ALTER TABLE CONTROL.DATASET_HEALTH ADD COLUMN IF NOT EXISTS HEALTH_REASON VARCHAR;
ALTER TABLE CONTROL.INCIDENT ADD COLUMN IF NOT EXISTS INCIDENT_KEY VARCHAR;
ALTER TABLE CONTROL.INCIDENT ADD COLUMN IF NOT EXISTS STAGE VARCHAR;

CREATE OR REPLACE VIEW CONTROL.SLA_EVALUATION_V AS
WITH BASE AS (
    SELECT
        P.DATASET_ID,
        P.STAGE,
        UPPER(P.CADENCE_TYPE) AS CADENCE_TYPE,
        P.MAX_LATENCY_SECONDS,
        P.MAX_FRESHNESS_SECONDS,
        P.EXPECTED_INTERVAL_SECONDS,
        P.DEADLINE_LOCAL_TIME,
        P.TIMEZONE,
        P.ENABLED AS POLICY_ENABLED,
        O.ENABLED AS DATASET_ENABLED,
        O.LAST_SOURCE_EVENT_AT,
        O.LAST_BRONZE_AT,
        O.LAST_SILVER_AT,
        O.LAST_GOLD_AT,
        O.SOURCE_TO_BRONZE_LATENCY_SECONDS,
        O.BRONZE_TO_SILVER_LATENCY_SECONDS,
        O.SILVER_TO_GOLD_LATENCY_SECONDS,
        O.LATEST_DATA_AT,
        CASE P.STAGE
            WHEN 'SOURCE_TO_BRONZE' THEN O.SOURCE_TO_BRONZE_LATENCY_SECONDS
            WHEN 'BRONZE_TO_SILVER' THEN O.BRONZE_TO_SILVER_LATENCY_SECONDS
            WHEN 'SILVER_TO_GOLD' THEN O.SILVER_TO_GOLD_LATENCY_SECONDS
            ELSE NULL
        END AS ACTUAL_LATENCY_SECONDS,
        IFF(
            P.STAGE = 'END_TO_END' AND O.LATEST_DATA_AT IS NOT NULL,
            GREATEST(0, DATEDIFF('SECOND', O.LATEST_DATA_AT, CURRENT_TIMESTAMP())),
            NULL
        ) AS ACTUAL_FRESHNESS_SECONDS,
        IFF(
            O.LAST_SOURCE_EVENT_AT IS NULL,
            NULL,
            GREATEST(0, DATEDIFF('SECOND', O.LAST_SOURCE_EVENT_AT, CURRENT_TIMESTAMP()))
        ) AS SOURCE_IDLE_SECONDS,
        CASE P.STAGE
            WHEN 'SOURCE_TO_BRONZE' THEN O.LAST_BRONZE_AT
            WHEN 'BRONZE_TO_SILVER' THEN O.LAST_SILVER_AT
            WHEN 'SILVER_TO_GOLD' THEN O.LAST_GOLD_AT
            WHEN 'END_TO_END' THEN COALESCE(O.LAST_GOLD_AT, O.LAST_SILVER_AT, O.LAST_BRONZE_AT)
        END AS LAST_STAGE_PUBLISHED_AT,
        CONVERT_TIMEZONE(COALESCE(P.TIMEZONE, 'UTC'), CURRENT_TIMESTAMP()) AS LOCAL_NOW
    FROM CONTROL.SLA_POLICY P
    JOIN CONTROL.DATASET_OBSERVABILITY_V O
      ON O.DATASET_ID = P.DATASET_ID
),
EVALUATED AS (
    SELECT
        *,
        CASE
            WHEN NOT POLICY_ENABLED OR NOT DATASET_ENABLED THEN 'DISABLED'
            WHEN CADENCE_TYPE NOT IN ('CONTINUOUS', 'INTERVAL', 'SCHEDULED_DEADLINE') THEN 'INVALID_POLICY'
            WHEN MAX_LATENCY_SECONDS IS NOT NULL
                 AND ACTUAL_LATENCY_SECONDS IS NOT NULL
                 AND ACTUAL_LATENCY_SECONDS > MAX_LATENCY_SECONDS THEN 'VIOLATED'
            WHEN STAGE = 'END_TO_END'
                 AND MAX_FRESHNESS_SECONDS IS NOT NULL
                 AND ACTUAL_FRESHNESS_SECONDS IS NOT NULL
                 AND ACTUAL_FRESHNESS_SECONDS > MAX_FRESHNESS_SECONDS THEN 'VIOLATED'
            WHEN CADENCE_TYPE = 'INTERVAL'
                 AND (EXPECTED_INTERVAL_SECONDS IS NULL OR EXPECTED_INTERVAL_SECONDS <= 0) THEN 'INVALID_POLICY'
            WHEN CADENCE_TYPE = 'INTERVAL'
                 AND LAST_SOURCE_EVENT_AT IS NULL THEN 'UNKNOWN'
            WHEN CADENCE_TYPE = 'INTERVAL'
                 AND SOURCE_IDLE_SECONDS > EXPECTED_INTERVAL_SECONDS + COALESCE(MAX_FRESHNESS_SECONDS, 0) THEN 'VIOLATED'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND (DEADLINE_LOCAL_TIME IS NULL OR TIMEZONE IS NULL) THEN 'INVALID_POLICY'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND LOCAL_NOW::TIME < DEADLINE_LOCAL_TIME THEN 'NOT_DUE'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND LAST_STAGE_PUBLISHED_AT IS NULL THEN 'VIOLATED'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND CONVERT_TIMEZONE(TIMEZONE, LAST_STAGE_PUBLISHED_AT)::DATE < LOCAL_NOW::DATE THEN 'VIOLATED'
            WHEN STAGE = 'END_TO_END' AND LATEST_DATA_AT IS NULL THEN 'UNKNOWN'
            ELSE 'PASS'
        END AS SLA_STATUS,
        CASE
            WHEN NOT POLICY_ENABLED OR NOT DATASET_ENABLED THEN 'policy or dataset disabled'
            WHEN CADENCE_TYPE NOT IN ('CONTINUOUS', 'INTERVAL', 'SCHEDULED_DEADLINE') THEN 'unsupported cadence type'
            WHEN MAX_LATENCY_SECONDS IS NOT NULL
                 AND ACTUAL_LATENCY_SECONDS IS NOT NULL
                 AND ACTUAL_LATENCY_SECONDS > MAX_LATENCY_SECONDS
                THEN 'stage latency exceeded threshold'
            WHEN STAGE = 'END_TO_END'
                 AND MAX_FRESHNESS_SECONDS IS NOT NULL
                 AND ACTUAL_FRESHNESS_SECONDS IS NOT NULL
                 AND ACTUAL_FRESHNESS_SECONDS > MAX_FRESHNESS_SECONDS
                THEN 'published data freshness exceeded threshold'
            WHEN CADENCE_TYPE = 'INTERVAL'
                 AND (EXPECTED_INTERVAL_SECONDS IS NULL OR EXPECTED_INTERVAL_SECONDS <= 0)
                THEN 'interval cadence requires EXPECTED_INTERVAL_SECONDS > 0'
            WHEN CADENCE_TYPE = 'INTERVAL' AND LAST_SOURCE_EVENT_AT IS NULL
                THEN 'no source event evidence is available'
            WHEN CADENCE_TYPE = 'INTERVAL'
                 AND SOURCE_IDLE_SECONDS > EXPECTED_INTERVAL_SECONDS + COALESCE(MAX_FRESHNESS_SECONDS, 0)
                THEN 'source has been idle beyond expected interval plus freshness tolerance'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND (DEADLINE_LOCAL_TIME IS NULL OR TIMEZONE IS NULL)
                THEN 'scheduled deadline requires deadline time and IANA timezone'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE' AND LOCAL_NOW::TIME < DEADLINE_LOCAL_TIME
                THEN 'daily deadline is not due yet'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE' AND LAST_STAGE_PUBLISHED_AT IS NULL
                THEN 'deadline passed but no successful stage publication exists'
            WHEN CADENCE_TYPE = 'SCHEDULED_DEADLINE'
                 AND CONVERT_TIMEZONE(TIMEZONE, LAST_STAGE_PUBLISHED_AT)::DATE < LOCAL_NOW::DATE
                THEN 'deadline passed without a publication on the current local date'
            WHEN STAGE = 'END_TO_END' AND LATEST_DATA_AT IS NULL
                THEN 'no published data timestamp is available'
            ELSE 'within policy'
        END AS SLA_REASON
    FROM BASE
)
SELECT
    DATASET_ID,
    STAGE,
    CADENCE_TYPE,
    POLICY_ENABLED,
    MAX_LATENCY_SECONDS,
    MAX_FRESHNESS_SECONDS,
    EXPECTED_INTERVAL_SECONDS,
    DEADLINE_LOCAL_TIME,
    TIMEZONE,
    ACTUAL_LATENCY_SECONDS,
    ACTUAL_FRESHNESS_SECONDS,
    SOURCE_IDLE_SECONDS,
    LAST_STAGE_PUBLISHED_AT,
    SLA_STATUS,
    SLA_REASON
FROM EVALUATED;

CREATE OR REPLACE VIEW CONTROL.SLA_VIOLATION_V AS
SELECT *
FROM CONTROL.SLA_EVALUATION_V
WHERE SLA_STATUS = 'VIOLATED';

CREATE OR REPLACE PROCEDURE CONTROL.REFRESH_DATASET_HEALTH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO CONTROL.DATASET_HEALTH AS TARGET
    USING (
        WITH POLICY AS (
            SELECT
                DATASET_ID,
                COUNT(*) AS POLICY_COUNT,
                COUNT_IF(SLA_STATUS = 'VIOLATED') AS VIOLATION_COUNT,
                COUNT_IF(SLA_STATUS = 'INVALID_POLICY') AS INVALID_POLICY_COUNT,
                COUNT_IF(SLA_STATUS = 'UNKNOWN') AS UNKNOWN_COUNT,
                LISTAGG(
                    IFF(SLA_STATUS IN ('VIOLATED', 'INVALID_POLICY', 'UNKNOWN'), STAGE || ': ' || SLA_REASON, NULL),
                    '; '
                ) WITHIN GROUP (ORDER BY STAGE) AS HEALTH_REASON
            FROM CONTROL.SLA_EVALUATION_V
            GROUP BY DATASET_ID
        ),
        OPEN_INCIDENT AS (
            SELECT DATASET_ID, COUNT(*) AS OPEN_INCIDENT_COUNT
            FROM CONTROL.INCIDENT
            WHERE STATUS = 'OPEN'
            GROUP BY DATASET_ID
        )
        SELECT
            O.DATASET_ID,
            CURRENT_TIMESTAMP() AS EVALUATED_AT,
            O.ACTIVE_VERSION,
            O.INGESTION_STATUS,
            O.SILVER_STATUS,
            O.GOLD_STATUS,
            O.LAST_SOURCE_EVENT_AT,
            O.LAST_BRONZE_AT,
            O.LAST_SILVER_AT,
            O.LAST_GOLD_AT,
            O.SOURCE_TO_BRONZE_LATENCY_SECONDS,
            O.BRONZE_TO_SILVER_LATENCY_SECONDS,
            O.SILVER_TO_GOLD_LATENCY_SECONDS,
            IFF(
                O.LATEST_DATA_AT IS NULL,
                NULL,
                GREATEST(0, DATEDIFF('SECOND', O.LATEST_DATA_AT, CURRENT_TIMESTAMP()))
            ) AS FRESHNESS_SECONDS,
            CASE
                WHEN P.POLICY_COUNT IS NULL THEN 'UNDEFINED'
                WHEN P.VIOLATION_COUNT > 0 THEN 'VIOLATED'
                WHEN P.INVALID_POLICY_COUNT > 0 THEN 'INVALID_POLICY'
                WHEN P.UNKNOWN_COUNT > 0 THEN 'UNKNOWN'
                ELSE 'PASS'
            END AS SLA_STATUS,
            P.HEALTH_REASON,
            COALESCE(I.OPEN_INCIDENT_COUNT, 0) AS OPEN_INCIDENT_COUNT,
            CASE
                WHEN O.ENABLED = FALSE THEN 'PAUSED'
                WHEN O.ACTIVE_VERSION IS NULL THEN 'DEVELOPMENT'
                WHEN O.INGESTION_STATUS = 'FAILED'
                  OR O.SILVER_STATUS = 'FAILED'
                  OR O.GOLD_STATUS = 'FAILED' THEN 'RED'
                WHEN P.VIOLATION_COUNT > 0 THEN 'RED'
                WHEN P.INVALID_POLICY_COUNT > 0 OR P.UNKNOWN_COUNT > 0 OR O.LATEST_DATA_AT IS NULL THEN 'YELLOW'
                ELSE 'GREEN'
            END AS OVERALL_STATUS
        FROM CONTROL.DATASET_OBSERVABILITY_V O
        LEFT JOIN POLICY P ON P.DATASET_ID = O.DATASET_ID
        LEFT JOIN OPEN_INCIDENT I ON I.DATASET_ID = O.DATASET_ID
    ) AS SOURCE
    ON TARGET.DATASET_ID = SOURCE.DATASET_ID
    WHEN MATCHED THEN UPDATE SET
        EVALUATED_AT = SOURCE.EVALUATED_AT,
        ACTIVE_VERSION = SOURCE.ACTIVE_VERSION,
        INGESTION_STATUS = SOURCE.INGESTION_STATUS,
        SILVER_STATUS = SOURCE.SILVER_STATUS,
        GOLD_STATUS = SOURCE.GOLD_STATUS,
        LAST_SOURCE_EVENT_AT = SOURCE.LAST_SOURCE_EVENT_AT,
        LAST_BRONZE_AT = SOURCE.LAST_BRONZE_AT,
        LAST_SILVER_AT = SOURCE.LAST_SILVER_AT,
        LAST_GOLD_AT = SOURCE.LAST_GOLD_AT,
        SOURCE_TO_BRONZE_LATENCY_SECONDS = SOURCE.SOURCE_TO_BRONZE_LATENCY_SECONDS,
        BRONZE_TO_SILVER_LATENCY_SECONDS = SOURCE.BRONZE_TO_SILVER_LATENCY_SECONDS,
        SILVER_TO_GOLD_LATENCY_SECONDS = SOURCE.SILVER_TO_GOLD_LATENCY_SECONDS,
        FRESHNESS_SECONDS = SOURCE.FRESHNESS_SECONDS,
        SLA_STATUS = SOURCE.SLA_STATUS,
        HEALTH_REASON = SOURCE.HEALTH_REASON,
        OPEN_INCIDENT_COUNT = SOURCE.OPEN_INCIDENT_COUNT,
        OVERALL_STATUS = SOURCE.OVERALL_STATUS,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        DATASET_ID, EVALUATED_AT, ACTIVE_VERSION,
        INGESTION_STATUS, SILVER_STATUS, GOLD_STATUS,
        LAST_SOURCE_EVENT_AT, LAST_BRONZE_AT, LAST_SILVER_AT, LAST_GOLD_AT,
        SOURCE_TO_BRONZE_LATENCY_SECONDS, BRONZE_TO_SILVER_LATENCY_SECONDS,
        SILVER_TO_GOLD_LATENCY_SECONDS, FRESHNESS_SECONDS,
        SLA_STATUS, HEALTH_REASON, OPEN_INCIDENT_COUNT, OVERALL_STATUS, UPDATED_AT
    ) VALUES (
        SOURCE.DATASET_ID, SOURCE.EVALUATED_AT, SOURCE.ACTIVE_VERSION,
        SOURCE.INGESTION_STATUS, SOURCE.SILVER_STATUS, SOURCE.GOLD_STATUS,
        SOURCE.LAST_SOURCE_EVENT_AT, SOURCE.LAST_BRONZE_AT, SOURCE.LAST_SILVER_AT, SOURCE.LAST_GOLD_AT,
        SOURCE.SOURCE_TO_BRONZE_LATENCY_SECONDS, SOURCE.BRONZE_TO_SILVER_LATENCY_SECONDS,
        SOURCE.SILVER_TO_GOLD_LATENCY_SECONDS, SOURCE.FRESHNESS_SECONDS,
        SOURCE.SLA_STATUS, SOURCE.HEALTH_REASON, SOURCE.OPEN_INCIDENT_COUNT,
        SOURCE.OVERALL_STATUS, CURRENT_TIMESTAMP()
    );

    RETURN 'DATASET_HEALTH refreshed';
END;
$$;

CREATE OR REPLACE PROCEDURE CONTROL.EVALUATE_DOMAIN_HEALTH()
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_ACTIVE_CONDITIONS NUMBER DEFAULT 0;
    V_OPEN_INCIDENTS NUMBER DEFAULT 0;
BEGIN
    CALL CONTROL.REFRESH_DATASET_HEALTH();

    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_ACTIVE_CONDITIONS (
        INCIDENT_KEY VARCHAR,
        DATASET_ID VARCHAR,
        INCIDENT_TYPE VARCHAR,
        STAGE VARCHAR,
        SEVERITY VARCHAR,
        REASON VARCHAR,
        LATEST_MESSAGE VARCHAR
    );

    INSERT INTO ESF_ACTIVE_CONDITIONS
    SELECT
        D.DATASET_ID || '|INGESTION_FAILURE|',
        D.DATASET_ID,
        'INGESTION_FAILURE',
        NULL,
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        'latest ingestion run failed',
        'Latest ingestion status is FAILED'
    FROM CONTROL.DATASET_OBSERVABILITY_V D
    WHERE D.ENABLED AND D.INGESTION_STATUS = 'FAILED'
    UNION ALL
    SELECT
        D.DATASET_ID || '|PIPELINE_FAILURE|',
        D.DATASET_ID,
        'PIPELINE_FAILURE',
        NULL,
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        'latest Bronze-to-Silver run failed',
        'Latest Silver pipeline status is FAILED'
    FROM CONTROL.DATASET_OBSERVABILITY_V D
    WHERE D.ENABLED AND D.SILVER_STATUS = 'FAILED'
    UNION ALL
    SELECT
        D.DATASET_ID || '|DBT_FAILURE|',
        D.DATASET_ID,
        'DBT_FAILURE',
        NULL,
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        'latest dbt run failed',
        'Latest dbt status is FAILED'
    FROM CONTROL.DATASET_OBSERVABILITY_V D
    WHERE D.ENABLED AND D.GOLD_STATUS = 'FAILED';

    INSERT INTO ESF_ACTIVE_CONDITIONS
    SELECT
        V.DATASET_ID || '|SLA_VIOLATION|' || V.STAGE,
        V.DATASET_ID,
        'SLA_VIOLATION',
        V.STAGE,
        IFF(D.CRITICALITY = 'CRITICAL', 'CRITICAL', IFF(D.CRITICALITY = 'HIGH', 'HIGH', 'MEDIUM')),
        V.SLA_REASON,
        V.STAGE || ': ' || V.SLA_REASON
    FROM CONTROL.SLA_VIOLATION_V V
    JOIN CONTROL.DATASET D ON D.DATASET_ID = V.DATASET_ID
    WHERE D.ENABLED;

    V_ACTIVE_CONDITIONS := (SELECT COUNT(*) FROM ESF_ACTIVE_CONDITIONS);

    UPDATE CONTROL.INCIDENT I
    SET
        SEVERITY = A.SEVERITY,
        STAGE = A.STAGE,
        REASON = A.REASON,
        LATEST_MESSAGE = A.LATEST_MESSAGE,
        UPDATED_AT = CURRENT_TIMESTAMP()
    FROM ESF_ACTIVE_CONDITIONS A
    WHERE I.INCIDENT_KEY = A.INCIDENT_KEY
      AND I.STATUS = 'OPEN';

    INSERT INTO CONTROL.INCIDENT (
        INCIDENT_ID, INCIDENT_KEY, DATASET_ID, INCIDENT_TYPE, STAGE,
        SEVERITY, STATUS, OPENED_AT, REASON, LATEST_MESSAGE
    )
    SELECT
        UUID_STRING(), A.INCIDENT_KEY, A.DATASET_ID, A.INCIDENT_TYPE, A.STAGE,
        A.SEVERITY, 'OPEN', CURRENT_TIMESTAMP(), A.REASON, A.LATEST_MESSAGE
    FROM ESF_ACTIVE_CONDITIONS A
    WHERE NOT EXISTS (
        SELECT 1
        FROM CONTROL.INCIDENT I
        WHERE I.INCIDENT_KEY = A.INCIDENT_KEY
          AND I.STATUS = 'OPEN'
    );

    UPDATE CONTROL.INCIDENT I
    SET
        STATUS = 'RESOLVED',
        RESOLVED_AT = CURRENT_TIMESTAMP(),
        LATEST_MESSAGE = 'Condition recovered',
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE I.STATUS = 'OPEN'
      AND I.INCIDENT_TYPE IN ('INGESTION_FAILURE', 'PIPELINE_FAILURE', 'DBT_FAILURE', 'SLA_VIOLATION')
      AND NOT EXISTS (
          SELECT 1
          FROM ESF_ACTIVE_CONDITIONS A
          WHERE A.INCIDENT_KEY = I.INCIDENT_KEY
      );

    CALL CONTROL.REFRESH_DATASET_HEALTH();
    V_OPEN_INCIDENTS := (SELECT COUNT(*) FROM CONTROL.INCIDENT WHERE STATUS = 'OPEN');

    RETURN OBJECT_CONSTRUCT(
        'active_conditions', V_ACTIVE_CONDITIONS,
        'open_incidents', V_OPEN_INCIDENTS,
        'evaluated_at', CURRENT_TIMESTAMP()
    );
END;
$$;

CREATE OR REPLACE VIEW CONTROL.DATASET_HEALTH_V AS
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    H.EVALUATED_AT,
    H.INGESTION_STATUS,
    H.SILVER_STATUS,
    H.GOLD_STATUS,
    H.LAST_SOURCE_EVENT_AT,
    H.LAST_BRONZE_AT,
    H.LAST_SILVER_AT,
    H.LAST_GOLD_AT,
    H.SOURCE_TO_BRONZE_LATENCY_SECONDS,
    H.BRONZE_TO_SILVER_LATENCY_SECONDS,
    H.SILVER_TO_GOLD_LATENCY_SECONDS,
    H.FRESHNESS_SECONDS,
    H.SLA_STATUS,
    H.HEALTH_REASON,
    H.OPEN_INCIDENT_COUNT,
    H.OVERALL_STATUS
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_HEALTH H ON H.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE VIEW CONTROL.DATASET_HEALTH_DETAIL_V AS
SELECT
    H.*,
    V.STAGE AS VIOLATED_STAGE,
    V.CADENCE_TYPE,
    V.ACTUAL_LATENCY_SECONDS,
    V.MAX_LATENCY_SECONDS,
    V.ACTUAL_FRESHNESS_SECONDS,
    V.MAX_FRESHNESS_SECONDS,
    V.EXPECTED_INTERVAL_SECONDS,
    V.DEADLINE_LOCAL_TIME,
    V.TIMEZONE,
    V.SLA_STATUS AS STAGE_SLA_STATUS,
    V.SLA_REASON AS STAGE_SLA_REASON
FROM CONTROL.DATASET_HEALTH_V H
LEFT JOIN CONTROL.SLA_EVALUATION_V V ON V.DATASET_ID = H.DATASET_ID;
