-- Release-readiness evidence and audit for explicit engineer-run cutovers.
-- This migration does not execute releases, approve candidates, or route transformation logic.

CREATE TABLE CONTROL.RELEASE_RUN (
    RELEASE_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    ACTION VARCHAR NOT NULL,
    FROM_VERSION VARCHAR NOT NULL,
    TO_VERSION VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    ALLOW_REVIEW_REQUIRED BOOLEAN DEFAULT FALSE,
    OPERATOR_REASON VARCHAR,
    STARTED_AT TIMESTAMP_LTZ NOT NULL,
    PREFLIGHT_AT TIMESTAMP_LTZ,
    CUTOVER_AT TIMESTAMP_LTZ,
    POSTFLIGHT_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ,
    PREFLIGHT_STATUS VARCHAR,
    PREFLIGHT_REASON VARCHAR,
    POSTFLIGHT_STATUS VARCHAR,
    POSTFLIGHT_REASON VARCHAR,
    FAILED_PHASE VARCHAR,
    OPERATOR_USER VARCHAR,
    OPERATOR_ROLE VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- One logical dataset should have one active version row and, while a candidate exists,
-- exactly one DEPLOYED candidate row matching DATASET.CANDIDATE_VERSION.
CREATE VIEW CONTROL.DATASET_VERSION_INVARIANT_V AS
WITH COUNTS AS (
    SELECT
        D.DATASET_ID,
        D.ACTIVE_VERSION,
        D.CANDIDATE_VERSION,
        COUNT_IF(UPPER(COALESCE(V.STATUS, '')) = 'ACTIVE') AS ACTIVE_STATUS_COUNT,
        COUNT_IF(UPPER(COALESCE(V.STATUS, '')) = 'DEPLOYED') AS DEPLOYED_STATUS_COUNT,
        COUNT_IF(
            UPPER(COALESCE(V.STATUS, '')) = 'ACTIVE'
            AND V.VERSION = D.ACTIVE_VERSION
        ) AS ACTIVE_POINTER_MATCH_COUNT,
        COUNT_IF(
            UPPER(COALESCE(V.STATUS, '')) = 'DEPLOYED'
            AND V.VERSION = D.CANDIDATE_VERSION
        ) AS CANDIDATE_POINTER_MATCH_COUNT,
        COUNT_IF(
            V.VERSION = D.CANDIDATE_VERSION
            AND UPPER(COALESCE(V.STATUS, '')) = 'RETIRED'
        ) AS CANDIDATE_RETIRED_COUNT
    FROM CONTROL.DATASET D
    LEFT JOIN CONTROL.DATASET_VERSION V
      ON V.DATASET_ID = D.DATASET_ID
    GROUP BY D.DATASET_ID, D.ACTIVE_VERSION, D.CANDIDATE_VERSION
)
SELECT
    *,
    CASE
        WHEN ACTIVE_VERSION IS NULL THEN 'FAILED'
        WHEN ACTIVE_STATUS_COUNT <> 1 THEN 'FAILED'
        WHEN ACTIVE_POINTER_MATCH_COUNT <> 1 THEN 'FAILED'
        WHEN DEPLOYED_STATUS_COUNT > 1 THEN 'FAILED'
        WHEN CANDIDATE_VERSION = ACTIVE_VERSION THEN 'FAILED'
        WHEN CANDIDATE_VERSION IS NULL AND DEPLOYED_STATUS_COUNT <> 0 THEN 'FAILED'
        WHEN CANDIDATE_VERSION IS NOT NULL AND DEPLOYED_STATUS_COUNT <> 1 THEN 'FAILED'
        WHEN CANDIDATE_VERSION IS NOT NULL AND CANDIDATE_POINTER_MATCH_COUNT <> 1 THEN 'FAILED'
        WHEN CANDIDATE_RETIRED_COUNT <> 0 THEN 'FAILED'
        ELSE 'PASS'
    END AS INVARIANT_STATUS,
    CASE
        WHEN ACTIVE_VERSION IS NULL THEN 'ACTIVE_VERSION is NULL'
        WHEN ACTIVE_STATUS_COUNT <> 1 THEN 'expected exactly one DATASET_VERSION row with STATUS=ACTIVE'
        WHEN ACTIVE_POINTER_MATCH_COUNT <> 1 THEN 'ACTIVE_VERSION does not match the unique ACTIVE DATASET_VERSION row'
        WHEN DEPLOYED_STATUS_COUNT > 1 THEN 'more than one DEPLOYED candidate version exists'
        WHEN CANDIDATE_VERSION = ACTIVE_VERSION THEN 'CANDIDATE_VERSION must differ from ACTIVE_VERSION'
        WHEN CANDIDATE_VERSION IS NULL AND DEPLOYED_STATUS_COUNT <> 0 THEN 'DEPLOYED candidate row exists without CANDIDATE_VERSION pointer'
        WHEN CANDIDATE_VERSION IS NOT NULL AND DEPLOYED_STATUS_COUNT <> 1 THEN 'candidate pointer requires exactly one DEPLOYED version row'
        WHEN CANDIDATE_VERSION IS NOT NULL AND CANDIDATE_POINTER_MATCH_COUNT <> 1 THEN 'CANDIDATE_VERSION does not match the DEPLOYED version row'
        WHEN CANDIDATE_RETIRED_COUNT <> 0 THEN 'CANDIDATE_VERSION points at a RETIRED version'
        ELSE 'version pointers and statuses are consistent'
    END AS INVARIANT_REASON
FROM COUNTS;

-- VERSION_VALIDATION has one row per explicit check rather than a hidden approval state.
-- Keep the latest result per check and summarize it without converting REVIEW_REQUIRED into PASS.
CREATE VIEW CONTROL.CANDIDATE_COMPARISON_STATUS_V AS
WITH RANKED AS (
    SELECT
        V.*,
        ROW_NUMBER() OVER (
            PARTITION BY DATASET_ID, ACTIVE_VERSION, CANDIDATE_VERSION, CHECK_NAME
            ORDER BY VALIDATED_AT DESC, VALIDATION_ID DESC
        ) AS RN
    FROM CONTROL.VERSION_VALIDATION V
),
LATEST AS (
    SELECT *
    FROM RANKED
    WHERE RN = 1
)
SELECT
    DATASET_ID,
    ACTIVE_VERSION,
    CANDIDATE_VERSION,
    MAX(VALIDATED_AT) AS VALIDATED_AT,
    COUNT(*) AS CHECK_COUNT,
    COUNT_IF(UPPER(STATUS) = 'PASS') AS PASS_COUNT,
    COUNT_IF(UPPER(STATUS) = 'REVIEW_REQUIRED') AS REVIEW_REQUIRED_COUNT,
    COUNT_IF(UPPER(STATUS) = 'FAIL') AS FAIL_COUNT,
    COUNT_IF(UPPER(STATUS) NOT IN ('PASS', 'REVIEW_REQUIRED', 'FAIL')) AS INVALID_STATUS_COUNT,
    CASE
        WHEN COUNT_IF(UPPER(STATUS) = 'FAIL') > 0 THEN 'FAILED'
        WHEN COUNT_IF(UPPER(STATUS) NOT IN ('PASS', 'REVIEW_REQUIRED', 'FAIL')) > 0 THEN 'FAILED'
        WHEN COUNT_IF(UPPER(STATUS) = 'REVIEW_REQUIRED') > 0 THEN 'REVIEW_REQUIRED'
        ELSE 'PASS'
    END AS COMPARISON_STATUS
FROM LATEST
GROUP BY DATASET_ID, ACTIVE_VERSION, CANDIDATE_VERSION;

-- Normalize the latest candidate runtime evidence without fabricating a common execution engine.
-- Stream/Task and batch implementations use PIPELINE_RUN; Dynamic Tables use native refresh history.
CREATE VIEW CONTROL.CANDIDATE_RUNTIME_STATUS_V AS
WITH LATEST_PIPELINE AS (
    SELECT
        DATASET_ID,
        VERSION,
        STATUS,
        COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) AS EVIDENCE_AT,
        RUN_ID,
        QUERY_ID
    FROM CONTROL.PIPELINE_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID, VERSION
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC, RUN_ID DESC
    ) = 1
)
SELECT
    V.DATASET_ID,
    V.VERSION,
    V.EXECUTION_MODEL,
    CASE
        WHEN V.EXECUTION_MODEL = 'dynamic_table' THEN R.SILVER_STATUS
        ELSE P.STATUS
    END AS RUNTIME_STATUS,
    CASE
        WHEN V.EXECUTION_MODEL = 'dynamic_table'
            THEN COALESCE(R.REFRESH_END_TIME, R.REFRESH_START_TIME, R.DATA_TIMESTAMP)
        ELSE P.EVIDENCE_AT
    END AS RUNTIME_EVIDENCE_AT,
    CASE
        WHEN V.EXECUTION_MODEL = 'dynamic_table' THEN R.QUERY_ID
        ELSE P.QUERY_ID
    END AS RUNTIME_QUERY_ID,
    P.RUN_ID AS PIPELINE_RUN_ID
FROM CONTROL.DATASET_VERSION V
LEFT JOIN LATEST_PIPELINE P
  ON P.DATASET_ID = V.DATASET_ID
 AND P.VERSION = V.VERSION
LEFT JOIN CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V R
  ON R.DATASET_ID = V.DATASET_ID
 AND R.VERSION = V.VERSION;

-- Release readiness is evidence, not approval. READY has no hard failures or warnings;
-- REVIEW_REQUIRED means only explicitly reviewable evidence remains; BLOCKED is fail-closed.
CREATE VIEW CONTROL.RELEASE_READINESS_V AS
SELECT
    D.DATASET_ID,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    I.INVARIANT_STATUS,
    I.INVARIANT_REASON,
    V.STATUS AS CANDIDATE_VERSION_STATUS,
    V.EXECUTION_MODEL AS CANDIDATE_EXECUTION_MODEL,
    R.RUNTIME_STATUS,
    R.RUNTIME_EVIDENCE_AT,
    R.RUNTIME_QUERY_ID,
    Q.DQ_STATUS,
    Q.CHECKED_AT AS DQ_CHECKED_AT,
    Q.FAILED_CHECKS AS DQ_FAILED_CHECKS,
    C.COMPARISON_STATUS,
    C.VALIDATED_AT AS COMPARISON_VALIDATED_AT,
    C.CHECK_COUNT AS COMPARISON_CHECK_COUNT,
    C.REVIEW_REQUIRED_COUNT,
    C.FAIL_COUNT AS COMPARISON_FAIL_COUNT,
    CASE
        WHEN I.INVARIANT_STATUS <> 'PASS' THEN 'BLOCKED'
        WHEN D.CANDIDATE_VERSION IS NULL THEN 'BLOCKED'
        WHEN V.VERSION IS NULL THEN 'BLOCKED'
        WHEN UPPER(COALESCE(V.STATUS, '')) <> 'DEPLOYED' THEN 'BLOCKED'
        WHEN R.RUNTIME_STATUS IS NULL THEN 'BLOCKED'
        WHEN UPPER(R.RUNTIME_STATUS) <> 'SUCCESS' THEN 'BLOCKED'
        WHEN Q.DQ_STATUS IS NULL THEN 'BLOCKED'
        WHEN UPPER(Q.DQ_STATUS) = 'FAILED' THEN 'BLOCKED'
        WHEN Q.CHECKED_AT < R.RUNTIME_EVIDENCE_AT THEN 'BLOCKED'
        WHEN C.COMPARISON_STATUS IS NULL THEN 'BLOCKED'
        WHEN C.COMPARISON_STATUS = 'FAILED' THEN 'BLOCKED'
        WHEN C.VALIDATED_AT < R.RUNTIME_EVIDENCE_AT THEN 'BLOCKED'
        WHEN UPPER(Q.DQ_STATUS) = 'WARNING' THEN 'REVIEW_REQUIRED'
        WHEN C.COMPARISON_STATUS = 'REVIEW_REQUIRED' THEN 'REVIEW_REQUIRED'
        ELSE 'READY'
    END AS READINESS_STATUS,
    CASE
        WHEN I.INVARIANT_STATUS <> 'PASS' THEN I.INVARIANT_REASON
        WHEN D.CANDIDATE_VERSION IS NULL THEN 'no candidate version is registered'
        WHEN V.VERSION IS NULL THEN 'candidate version row is missing'
        WHEN UPPER(COALESCE(V.STATUS, '')) <> 'DEPLOYED' THEN 'candidate version is not in DEPLOYED status'
        WHEN R.RUNTIME_STATUS IS NULL THEN 'candidate runtime evidence is missing'
        WHEN UPPER(R.RUNTIME_STATUS) <> 'SUCCESS' THEN 'latest candidate runtime evidence is not SUCCESS'
        WHEN Q.DQ_STATUS IS NULL THEN 'candidate DQ evidence is missing'
        WHEN UPPER(Q.DQ_STATUS) = 'FAILED' THEN 'latest candidate DQ evidence failed'
        WHEN Q.CHECKED_AT < R.RUNTIME_EVIDENCE_AT THEN 'candidate DQ evidence is older than latest runtime evidence'
        WHEN C.COMPARISON_STATUS IS NULL THEN 'active-vs-candidate comparison evidence is missing'
        WHEN C.COMPARISON_STATUS = 'FAILED' THEN 'active-vs-candidate comparison failed'
        WHEN C.VALIDATED_AT < R.RUNTIME_EVIDENCE_AT THEN 'comparison evidence is older than latest runtime evidence'
        WHEN UPPER(Q.DQ_STATUS) = 'WARNING' THEN 'candidate DQ has WARN evidence that requires explicit review acceptance'
        WHEN C.COMPARISON_STATUS = 'REVIEW_REQUIRED' THEN 'comparison evidence requires explicit review acceptance'
        ELSE 'candidate runtime, DQ, comparison and version invariants are ready'
    END AS READINESS_REASON
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_VERSION_INVARIANT_V I
  ON I.DATASET_ID = D.DATASET_ID
LEFT JOIN CONTROL.DATASET_VERSION V
  ON V.DATASET_ID = D.DATASET_ID
 AND V.VERSION = D.CANDIDATE_VERSION
LEFT JOIN CONTROL.CANDIDATE_RUNTIME_STATUS_V R
  ON R.DATASET_ID = D.DATASET_ID
 AND R.VERSION = D.CANDIDATE_VERSION
LEFT JOIN CONTROL.DQ_LATEST_RUN_V Q
  ON Q.DATASET_ID = D.DATASET_ID
 AND Q.VERSION = D.CANDIDATE_VERSION
LEFT JOIN CONTROL.CANDIDATE_COMPARISON_STATUS_V C
  ON C.DATASET_ID = D.DATASET_ID
 AND C.ACTIVE_VERSION = D.ACTIVE_VERSION
 AND C.CANDIDATE_VERSION = D.CANDIDATE_VERSION;

CREATE VIEW CONTROL.RELEASE_RUN_LATEST_V AS
SELECT *
FROM CONTROL.RELEASE_RUN
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DATASET_ID
    ORDER BY STARTED_AT DESC, RELEASE_ID DESC
) = 1;
