CREATE SCHEMA IF NOT EXISTS CONTROL;

CREATE TABLE IF NOT EXISTS CONTROL.DATASET (
    DATASET_ID VARCHAR NOT NULL,
    SOURCE_ID VARCHAR NOT NULL,
    DATASET_NAME VARCHAR NOT NULL,
    OWNER VARCHAR,
    CRITICALITY VARCHAR DEFAULT 'MEDIUM',
    PATTERN VARCHAR NOT NULL,
    ENABLED BOOLEAN DEFAULT TRUE,
    BRONZE_RELATION VARCHAR,
    PUBLISHED_SILVER_RELATION VARCHAR,
    ACTIVE_VERSION VARCHAR,
    CANDIDATE_VERSION VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.DATASET_VERSION (
    DATASET_ID VARCHAR NOT NULL,
    VERSION VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    GIT_COMMIT VARCHAR,
    HISTORY_RELATION VARCHAR,
    CURRENT_RELATION VARCHAR,
    APPLY_OBJECT VARCHAR,
    TASK_OBJECT VARCHAR,
    STREAM_OBJECT VARCHAR,
    DEPLOYED_AT TIMESTAMP_LTZ,
    ACTIVATED_AT TIMESTAMP_LTZ,
    RETIRED_AT TIMESTAMP_LTZ,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.SLA_POLICY (
    DATASET_ID VARCHAR NOT NULL,
    STAGE VARCHAR NOT NULL,
    CADENCE_TYPE VARCHAR NOT NULL,
    MAX_LATENCY_SECONDS NUMBER(38,0),
    MAX_FRESHNESS_SECONDS NUMBER(38,0),
    EXPECTED_INTERVAL_SECONDS NUMBER(38,0),
    DEADLINE_LOCAL_TIME TIME,
    TIMEZONE VARCHAR,
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.INGESTION_RUN (
    RUN_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    SOURCE_ID VARCHAR,
    INGESTION_TYPE VARCHAR,
    STATUS VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ,
    SOURCE_MIN_TIMESTAMP TIMESTAMP_LTZ,
    SOURCE_MAX_TIMESTAMP TIMESTAMP_LTZ,
    BRONZE_PUBLISHED_AT TIMESTAMP_LTZ,
    ROWS_RECEIVED NUMBER(38,0),
    EXTERNAL_RUN_ID VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.PIPELINE_RUN (
    RUN_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    VERSION VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ,
    BRONZE_DATA_MIN_AT TIMESTAMP_LTZ,
    BRONZE_DATA_MAX_AT TIMESTAMP_LTZ,
    SILVER_DATA_MAX_AT TIMESTAMP_LTZ,
    SILVER_PUBLISHED_AT TIMESTAMP_LTZ,
    ROWS_READ NUMBER(38,0),
    ROWS_INSERTED NUMBER(38,0),
    ROWS_UPDATED NUMBER(38,0),
    ROWS_DELETED NUMBER(38,0),
    QUERY_ID VARCHAR,
    TASK_NAME VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.DBT_RUN (
    RUN_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR,
    MODEL_NAME VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ,
    SILVER_DATA_MAX_AT TIMESTAMP_LTZ,
    GOLD_DATA_MAX_AT TIMESTAMP_LTZ,
    GOLD_PUBLISHED_AT TIMESTAMP_LTZ,
    ROWS_AFFECTED NUMBER(38,0),
    GIT_COMMIT VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.DATASET_HEALTH (
    DATASET_ID VARCHAR NOT NULL,
    EVALUATED_AT TIMESTAMP_LTZ NOT NULL,
    ACTIVE_VERSION VARCHAR,
    INGESTION_STATUS VARCHAR,
    SILVER_STATUS VARCHAR,
    GOLD_STATUS VARCHAR,
    LAST_SOURCE_EVENT_AT TIMESTAMP_LTZ,
    LAST_BRONZE_AT TIMESTAMP_LTZ,
    LAST_SILVER_AT TIMESTAMP_LTZ,
    LAST_GOLD_AT TIMESTAMP_LTZ,
    SOURCE_TO_BRONZE_LATENCY_SECONDS NUMBER(38,0),
    BRONZE_TO_SILVER_LATENCY_SECONDS NUMBER(38,0),
    SILVER_TO_GOLD_LATENCY_SECONDS NUMBER(38,0),
    FRESHNESS_SECONDS NUMBER(38,0),
    SLA_STATUS VARCHAR,
    OPEN_INCIDENT_COUNT NUMBER(38,0) DEFAULT 0,
    OVERALL_STATUS VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.INCIDENT (
    INCIDENT_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    INCIDENT_TYPE VARCHAR NOT NULL,
    SEVERITY VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    OPENED_AT TIMESTAMP_LTZ NOT NULL,
    RESOLVED_AT TIMESTAMP_LTZ,
    REASON VARCHAR,
    LATEST_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.REPAIR_RUN (
    REPAIR_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    REPAIR_TYPE VARCHAR NOT NULL,
    REASON VARCHAR,
    REQUESTED_FROM TIMESTAMP_LTZ,
    REQUESTED_TO TIMESTAMP_LTZ,
    STARTED_AT TIMESTAMP_LTZ,
    COMPLETED_AT TIMESTAMP_LTZ,
    STATUS VARCHAR NOT NULL,
    ROWS_RECOVERED NUMBER(38,0),
    OPERATOR VARCHAR,
    GIT_COMMIT VARCHAR,
    EXTERNAL_RUN_ID VARCHAR,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CONTROL.VERSION_VALIDATION (
    VALIDATION_ID VARCHAR NOT NULL,
    DATASET_ID VARCHAR NOT NULL,
    ACTIVE_VERSION VARCHAR,
    CANDIDATE_VERSION VARCHAR NOT NULL,
    CHECK_NAME VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    ACTIVE_VALUE VARCHAR,
    CANDIDATE_VALUE VARCHAR,
    DIFFERENCE_VALUE VARCHAR,
    DETAILS VARIANT,
    VALIDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Pattern-specific state should use dedicated tables when needed.
-- Do not add SQL Server LSNs, Kafka offsets, API cursors and full-refresh
-- checkpoints to one universal state table merely for uniformity.
