CREATE OR REPLACE VIEW CONTROL.DATASET_OBSERVABILITY_V AS
WITH LATEST_INGESTION AS (
    SELECT *
    FROM CONTROL.INGESTION_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_PIPELINE AS (
    SELECT *
    FROM CONTROL.PIPELINE_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_DBT AS (
    SELECT *
    FROM CONTROL.DBT_RUN
    WHERE DATASET_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
)
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    I.STATUS AS INGESTION_STATUS,
    P.STATUS AS SILVER_STATUS,
    B.STATUS AS GOLD_STATUS,
    I.SOURCE_MAX_TIMESTAMP AS LAST_SOURCE_EVENT_AT,
    I.BRONZE_PUBLISHED_AT AS LAST_BRONZE_AT,
    P.SILVER_PUBLISHED_AT AS LAST_SILVER_AT,
    B.GOLD_PUBLISHED_AT AS LAST_GOLD_AT,
    IFF(
        I.SOURCE_MAX_TIMESTAMP IS NULL OR I.BRONZE_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', I.SOURCE_MAX_TIMESTAMP, I.BRONZE_PUBLISHED_AT)
    ) AS SOURCE_TO_BRONZE_LATENCY_SECONDS,
    IFF(
        P.BRONZE_DATA_MAX_AT IS NULL OR P.SILVER_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', P.BRONZE_DATA_MAX_AT, P.SILVER_PUBLISHED_AT)
    ) AS BRONZE_TO_SILVER_LATENCY_SECONDS,
    IFF(
        B.SILVER_DATA_MAX_AT IS NULL OR B.GOLD_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', B.SILVER_DATA_MAX_AT, B.GOLD_PUBLISHED_AT)
    ) AS SILVER_TO_GOLD_LATENCY_SECONDS,
    COALESCE(B.GOLD_DATA_MAX_AT, P.SILVER_DATA_MAX_AT, I.SOURCE_MAX_TIMESTAMP) AS LATEST_DATA_AT,
    I.RUN_ID AS LAST_INGESTION_RUN_ID,
    P.RUN_ID AS LAST_PIPELINE_RUN_ID,
    B.RUN_ID AS LAST_DBT_RUN_ID
FROM CONTROL.DATASET D
LEFT JOIN LATEST_INGESTION I ON I.DATASET_ID = D.DATASET_ID
LEFT JOIN LATEST_PIPELINE P ON P.DATASET_ID = D.DATASET_ID
LEFT JOIN LATEST_DBT B ON B.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE VIEW CONTROL.DATASET_HEALTH_V AS
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    H.EVALUATED_AT,
    H.INGESTION_STATUS,
    H.SILVER_STATUS,
    H.GOLD_STATUS,
    H.LAST_SOURCE_EVENT_AT,
    H.LAST_BRONZE_AT,
    H.LAST_SILVER_AT,
    H.LAST_GOLD_AT,
    H.SOURCE_TO_BRONZE_LATENCY_SECONDS,
    H.BRONZE_TO_SILVER_LATENCY_SECONDS,
    H.SILVER_TO_GOLD_LATENCY_SECONDS,
    H.FRESHNESS_SECONDS,
    H.SLA_STATUS,
    H.OPEN_INCIDENT_COUNT,
    H.OVERALL_STATUS
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_HEALTH H ON H.DATASET_ID = D.DATASET_ID;

CREATE OR REPLACE VIEW CONTROL.OPEN_INCIDENT_V AS
SELECT
    INCIDENT_ID,
    DATASET_ID,
    INCIDENT_TYPE,
    SEVERITY,
    STATUS,
    OPENED_AT,
    REASON,
    LATEST_MESSAGE,
    UPDATED_AT
FROM CONTROL.INCIDENT
WHERE STATUS = 'OPEN';
