-- Stable read-only contract for enterprise monitoring.
-- Domain health remains owned and evaluated inside this domain database.
-- Enterprise monitoring should UNION these views; it must not write back into domain CONTROL schemas.

CREATE OR REPLACE VIEW CONTROL.ENTERPRISE_HEALTH_EXPORT_V AS
SELECT
    '__PROJECT_CODE__'::VARCHAR AS DOMAIN_CODE,
    CURRENT_DATABASE() AS DOMAIN_DATABASE,
    DATASET_ID,
    SOURCE_ID,
    DATASET_NAME,
    OWNER,
    CRITICALITY,
    PATTERN,
    ENABLED,
    LIFECYCLE_STATUS,
    ACTIVE_VERSION,
    CANDIDATE_VERSION,
    EVALUATED_AT,
    INGESTION_STATUS,
    SILVER_STATUS,
    GOLD_STATUS,
    LAST_SOURCE_EVENT_AT,
    LAST_BRONZE_AT,
    LAST_SILVER_AT,
    LAST_GOLD_AT,
    SOURCE_TO_BRONZE_LATENCY_SECONDS,
    BRONZE_TO_SILVER_LATENCY_SECONDS,
    SILVER_TO_GOLD_LATENCY_SECONDS,
    FRESHNESS_SECONDS,
    SLA_STATUS,
    HEALTH_REASON,
    OPEN_INCIDENT_COUNT,
    OVERALL_STATUS
FROM CONTROL.DATASET_HEALTH_V;

CREATE OR REPLACE VIEW CONTROL.DOMAIN_HEALTH_SUMMARY_V AS
SELECT
    '__PROJECT_CODE__'::VARCHAR AS DOMAIN_CODE,
    CURRENT_DATABASE() AS DOMAIN_DATABASE,
    CURRENT_TIMESTAMP() AS OBSERVED_AT,
    COUNT(*) AS TOTAL_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'ACTIVE') AS ACTIVE_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'PAUSED') AS PAUSED_DATASET_COUNT,
    COUNT_IF(LIFECYCLE_STATUS = 'DECOMMISSIONED') AS DECOMMISSIONED_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'GREEN') AS GREEN_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'YELLOW') AS YELLOW_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'RED') AS RED_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS = 'DEVELOPMENT') AS DEVELOPMENT_DATASET_COUNT,
    COUNT_IF(OVERALL_STATUS IS NULL) AS UNASSESSED_DATASET_COUNT,
    COALESCE(SUM(OPEN_INCIDENT_COUNT), 0) AS OPEN_INCIDENT_COUNT,
    MAX(EVALUATED_AT) AS LAST_EVALUATED_AT
FROM CONTROL.ENTERPRISE_HEALTH_EXPORT_V;
