-- Normalize native Dynamic Table refresh evidence without fabricating CONTROL.PIPELINE_RUN rows.
-- INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY is database-scoped and retains recent refresh history.

CREATE VIEW CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V AS
WITH REFRESH_HISTORY AS (
    SELECT
        NAME,
        SCHEMA_NAME,
        DATABASE_NAME,
        STATE,
        STATE_CODE,
        STATE_MESSAGE,
        QUERY_ID,
        DATA_TIMESTAMP,
        REFRESH_START_TIME,
        REFRESH_END_TIME,
        COMPLETION_TARGET,
        QUALIFIED_NAME
    FROM TABLE(
        INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
            DATA_TIMESTAMP_START => DATEADD('DAY', -7, CURRENT_TIMESTAMP()),
            RESULT_LIMIT => 10000
        )
    )
    WHERE STATE <> 'SCHEDULED'
),
MATCHED AS (
    SELECT
        V.DATASET_ID,
        V.VERSION,
        V.PRIMARY_RUNTIME_OBJECT,
        R.STATE AS REFRESH_STATE,
        R.STATE_CODE,
        R.STATE_MESSAGE,
        R.QUERY_ID,
        R.DATA_TIMESTAMP,
        R.REFRESH_START_TIME,
        R.REFRESH_END_TIME,
        R.COMPLETION_TARGET,
        CASE
            WHEN R.STATE IN ('SUCCEEDED', 'SKIPPED') THEN 'SUCCESS'
            WHEN R.STATE IN ('FAILED', 'CANCELLED', 'UPSTREAM_FAILED') THEN 'FAILED'
            WHEN R.STATE = 'EXECUTING' THEN 'RUNNING'
            ELSE 'UNKNOWN'
        END AS SILVER_STATUS
    FROM CONTROL.DATASET_VERSION V
    JOIN REFRESH_HISTORY R
      ON UPPER(V.PRIMARY_RUNTIME_OBJECT) = UPPER(R.SCHEMA_NAME || '.' || R.NAME)
    WHERE V.EXECUTION_MODEL = 'dynamic_table'
)
SELECT *
FROM MATCHED
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DATASET_ID, VERSION
    ORDER BY COALESCE(REFRESH_END_TIME, REFRESH_START_TIME, DATA_TIMESTAMP) DESC
) = 1;

-- Replace only the operational normalization view. The existing health refresh procedure reads
-- this stable view at runtime, so no fake Dynamic Table pipeline-run ledger is required.
CREATE OR REPLACE VIEW CONTROL.DATASET_OBSERVABILITY_V COPY GRANTS AS
WITH LATEST_INGESTION AS (
    SELECT *
    FROM CONTROL.INGESTION_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_PIPELINE AS (
    SELECT *
    FROM CONTROL.PIPELINE_RUN
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID, VERSION
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
),
LATEST_DBT AS (
    SELECT *
    FROM CONTROL.DBT_RUN
    WHERE DATASET_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET_ID
        ORDER BY COALESCE(COMPLETED_AT, STARTED_AT, CREATED_AT) DESC
    ) = 1
)
SELECT
    D.DATASET_ID,
    D.SOURCE_ID,
    D.DATASET_NAME,
    D.OWNER,
    D.CRITICALITY,
    D.PATTERN,
    D.ENABLED,
    D.ACTIVE_VERSION,
    D.CANDIDATE_VERSION,
    D.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION,
    V.EXECUTION_MODEL AS ACTIVE_EXECUTION_MODEL,
    I.STATUS AS INGESTION_STATUS,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', R.SILVER_STATUS, P.STATUS) AS SILVER_STATUS,
    B.STATUS AS GOLD_STATUS,
    I.SOURCE_MAX_TIMESTAMP AS LAST_SOURCE_EVENT_AT,
    I.BRONZE_PUBLISHED_AT AS LAST_BRONZE_AT,
    IFF(
        V.EXECUTION_MODEL = 'dynamic_table',
        COALESCE(R.REFRESH_END_TIME, R.REFRESH_START_TIME),
        P.SILVER_PUBLISHED_AT
    ) AS LAST_SILVER_AT,
    B.GOLD_PUBLISHED_AT AS LAST_GOLD_AT,
    IFF(
        I.SOURCE_MAX_TIMESTAMP IS NULL OR I.BRONZE_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', I.SOURCE_MAX_TIMESTAMP, I.BRONZE_PUBLISHED_AT)
    ) AS SOURCE_TO_BRONZE_LATENCY_SECONDS,
    IFF(
        V.EXECUTION_MODEL = 'dynamic_table',
        IFF(
            R.DATA_TIMESTAMP IS NULL OR R.REFRESH_END_TIME IS NULL,
            NULL,
            DATEDIFF('SECOND', R.DATA_TIMESTAMP, R.REFRESH_END_TIME)
        ),
        IFF(
            P.BRONZE_DATA_MAX_AT IS NULL OR P.SILVER_PUBLISHED_AT IS NULL,
            NULL,
            DATEDIFF('SECOND', P.BRONZE_DATA_MAX_AT, P.SILVER_PUBLISHED_AT)
        )
    ) AS BRONZE_TO_SILVER_LATENCY_SECONDS,
    IFF(
        B.SILVER_DATA_MAX_AT IS NULL OR B.GOLD_PUBLISHED_AT IS NULL,
        NULL,
        DATEDIFF('SECOND', B.SILVER_DATA_MAX_AT, B.GOLD_PUBLISHED_AT)
    ) AS SILVER_TO_GOLD_LATENCY_SECONDS,
    COALESCE(
        B.GOLD_DATA_MAX_AT,
        IFF(V.EXECUTION_MODEL = 'dynamic_table', R.DATA_TIMESTAMP, P.SILVER_DATA_MAX_AT),
        I.SOURCE_MAX_TIMESTAMP
    ) AS LATEST_DATA_AT,
    I.RUN_ID AS LAST_INGESTION_RUN_ID,
    IFF(V.EXECUTION_MODEL = 'dynamic_table', NULL, P.RUN_ID) AS LAST_PIPELINE_RUN_ID,
    B.RUN_ID AS LAST_DBT_RUN_ID
FROM CONTROL.DATASET D
LEFT JOIN CONTROL.DATASET_VERSION V
  ON V.DATASET_ID = D.DATASET_ID
 AND V.VERSION = D.ACTIVE_VERSION
LEFT JOIN LATEST_INGESTION I
  ON I.DATASET_ID = D.DATASET_ID
LEFT JOIN LATEST_PIPELINE P
  ON P.DATASET_ID = D.DATASET_ID
 AND P.VERSION = D.ACTIVE_VERSION
LEFT JOIN CONTROL.DYNAMIC_TABLE_REFRESH_STATUS_V R
  ON R.DATASET_ID = D.DATASET_ID
 AND R.VERSION = D.ACTIVE_VERSION
LEFT JOIN LATEST_DBT B
  ON B.DATASET_ID = D.DATASET_ID;
