mixed_strategy_project:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: offline
      user: offline
      password: offline
      role: OFFLINE
      database: CI_EXAMPLE
      warehouse: CI_EXAMPLE_TRANSFORM_WH
      schema: SILVER_STAGING
      threads: 1
